import test from 'node:test';
import assert from 'node:assert/strict';
import {cancelIntervention,finishCancellationPlanning} from '../lib/intervention-cancellation.js';
import {reassignPlanning,planningOriginals} from '../lib/planning-reassign.js';
function setup(){const x={id:'i',status:'planifiee',number:'INT-1',photos:[]};const e={id:'e',kind:'intervention',linkId:'i',start:'2026-09-28T08:00:00',end:'2026-09-28T10:00:00',teamIds:['p']};return {x,ui:{data:{interventions:[x],events:[e],people:[]},user:{displayName:'Ignazio'},canPlan:()=>true,save:async()=>{}}};}
test('cancel keeps record and reason, removes booking without creating actual hours or report',async()=>{const {x,ui}=setup();await cancelIntervention(ui,x,'Client : accès fonctionnel');assert.equal(x.status,'annulee');assert.equal(ui.data.events.length,0);assert.equal(x.cancelledPlanning.length,1);assert.equal(x.actualStart,undefined);assert.equal(x.cancellationPlanningPending,false);assert.equal(ui.data.interventions.length,1);});
test('permissions, reason, completed records and real hours are protected',async()=>{for(const modify of [u=>u.canPlan=()=>false,u=>u.data.interventions[0].status='terminee',u=>u.data.interventions[0].actualStart='2026-09-28T08:00',u=>u.data.events[0].actualStart='2026-09-28T08:00']){const {x,ui}=setup();modify(ui);await assert.rejects(cancelIntervention(ui,x,'motif'));assert.equal(ui.data.events.length,1);}const {x,ui}=setup();await assert.rejects(cancelIntervention(ui,x,' '));});
test('failed record save restores local state; failed event save can safely retry',async()=>{const {x,ui}=setup();ui.save=async()=>{throw Error('offline');};await assert.rejects(cancelIntervention(ui,x,'motif'));assert.equal(x.status,'planifiee');assert.equal(x.cancelledAt,undefined);ui.save=async k=>{if(k==='events')throw Error('offline');};await assert.rejects(cancelIntervention(ui,x,'motif'));assert.equal(x.status,'annulee');assert.equal(x.cancellationPlanningPending,true);assert.equal(ui.data.events.length,1);ui.save=async()=>{};await finishCancellationPlanning(ui,x);assert.equal(ui.data.events.length,0);assert.equal(x.cancellationPlanningPending,false);});
test('cancelling priority booking restores displaced project hours',async()=>{const {x,ui}=setup();const p={id:'p-event',kind:'project',linkId:'project',start:'2026-09-28T08:00:00',end:'2026-09-28T17:00:00',teamIds:['p']};ui.data.events=reassignPlanning([p],ui.data.events,[],[]);await cancelIntervention(ui,x,'client');assert.deepEqual(planningOriginals(ui.data.events).map(e=>e.id),['p-event']);assert.equal(ui.data.events[0].start,p.start);assert.equal(ui.data.events[0].end,p.end);});
