const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function eventProjectIds(e){return e.kind==='project'?[...new Set([e.linkId,...(e.additionalProjectIds||[])].filter(Boolean))]:[];}
export function projectEventLabel(e,projects){return eventProjectIds(e).map(id=>projects.find(p=>p.id===id)?.name||id).join(' + ')||e.title||'';}
export function mountPlanningAffairs(ui,e){
 const box=document.createElement('section');box.id='planningAffairs';box.className='panel';
 box.innerHTML=`<h3>Plusieurs affaires dans ce rendez-vous</h3><p>Une seule équipe et un seul bloc au calendrier. Cochez les autres affaires réalisées pendant cette journée.</p><label>Nom court du rendez-vous<input id="eventGroupTitle" placeholder="Ex. UCPA · Patinoire" value="${esc(e.groupTitle||'')}"></label><details><summary>Ajouter / retirer des affaires</summary>${ui.c.getCatalog().projects.map(p=>`<label class="inline"><input type="checkbox" data-linked-affair value="${esc(p.id)}" ${(e.additionalProjectIds||[]).includes(p.id)?'checked':''}> ${esc(p.name)}</label>`).join('')}</details><p class="muted">Les heures de l’équipe sont comptées une fois. Pour répartir précisément les heures entre affaires, utilisez des créneaux séparés ou les rapports propres à chaque affaire.</p>`;
 const mission=document.createElement('section');mission.className='panel';mission.id='planningMission';
 mission.innerHTML=`<details><summary>Apprentis : vendredi jusqu’à 16 h</summary><p>Choix pour les vendredis de ce rendez-vous uniquement. Saisissez une fin à 16 h ou plus et une pause de 1 h pour la journée complète. Seuls les salariés affectés à l’équipe sont concernés.</p>${ui.data?.people?.filter(p=>p.active!==false&&(p.role==='apprenti'||Number(p.weeklyTarget)===35)).map(p=>`<label class="inline"><input type="checkbox" data-friday-extended value="${esc(p.id)}" ${(e.fridayExtendedIds||[]).includes(p.id)?'checked':''}> ${esc(p.name)} · vendredi jusqu’à 16 h</label>`).join('')||''}</details><h3>Ce passage sur place</h3><label>Objet court du rendez-vous<input id="eventPurpose" placeholder="Ex. Recherche de panne · éclairage du hall" value="${esc(e.purpose||'')}"></label><label>À faire / consignes<textarea id="eventInstructions" rows="3" placeholder="Expliquez le problème, les travaux à effectuer et les précautions utiles.">${esc(e.instructions||'')}</textarea></label><p class="muted">Visible par l’équipe en touchant ce rendez-vous dans le calendrier. Ces consignes concernent ce passage uniquement.</p>`;
 document.getElementById('eventForm').querySelector('.teamAssignBox').before(mission,box);
 const sync=()=>{const [kind,id]=document.getElementById('eventLink').value.split('|');box.hidden=kind!=='project';box.querySelectorAll('[data-linked-affair]').forEach(cb=>{cb.disabled=cb.value===id;});};
 document.getElementById('eventLink').addEventListener('change',sync);sync();
}
export function readPlanningAffairs(kind,linkId){return {fridayExtendedIds:[...document.querySelectorAll('[data-friday-extended]:checked')].map(cb=>cb.value),additionalProjectIds:kind==='project'?[...document.querySelectorAll('[data-linked-affair]:checked')].map(cb=>cb.value).filter(id=>id!==linkId):[],groupTitle:kind==='project'?document.getElementById('eventGroupTitle').value.trim():'',purpose:document.getElementById('eventPurpose').value.trim(),instructions:document.getElementById('eventInstructions').value.trim()};}
