import test from 'node:test';import assert from 'node:assert/strict';
import {shortWorkLabel,payrollCells} from '../lib/payroll-sheet.js';
import {validateDepot,depotOrder} from '../commandes/depot.js';
test('payroll hides Graph ids and separates work from all absence categories',()=>{assert.equal(shortWorkLabel('Chantier · 01VXF2LY2D5ZKAHBZNIBBLHEE45KRS67IW · 2026-001172_ANTIN_PARIS_12'),'2026-001172 ANTIN PARIS 12');assert.equal(shortWorkLabel('Intervention · INT-2026-0002 · Client adresse privée'),'INT-2026-0002');for(const [nature,index] of [['Travail',0],['Maladie',1],['Sans solde',2],['Congés payés',3],['École',4],['Fermeture à qualifier',5]]){const cells=payrollCells({nature,hours:7});assert.equal(cells[index],7);assert.equal(cells.reduce((a,b)=>a+b,0),7);}});
test('depot must identify job, quantities, carton count and confirmed collector before recovered status',()=>{const d={number:'DEP-TEST',projectId:'p',projectName:'2026-001172 ANTIN',boxes:2,state:'À préparer',recipient:'',date:'2026-09-14',items:[{reference:'X',description:'Prise',quantity:'4',unit:'U'}]};validateDepot(d);assert.equal(depotOrder(d).internal,true);assert.equal(depotOrder(d).availability,'À préparer');assert.throws(()=>validateDepot({...d,state:'Récupéré'}),/personne/);validateDepot({...d,state:'Récupéré',recipient:'Ruben',collectedAt:'2026-09-14'});assert.throws(()=>validateDepot({...d,boxes:0}),/cartons/);assert.throws(()=>validateDepot({...d,items:[{description:'Prise',quantity:'-2'}]}),/quantité/);});
test('depot save writes PDF under selected job then a separate tracking revision',async()=>{
 const {JSDOM}=await import('jsdom');const {readFile}=await import('node:fs/promises');const {mountDepot}=await import('../commandes/depot.js');const oldDocument=globalThis.document,oldFetch=globalThis.fetch;const dom=new JSDOM('<section id="depotPage"></section>');globalThis.document=dom.window.document;globalThis.fetch=async u=>{const b=await readFile(new URL(u).pathname);return {ok:true,arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)};};const paths=[],writes=[];let authorized=0;
 try{const g={folder:async(parent,name)=>{paths.push([parent,name]);return {id:parent+'/'+name};},children:async()=>[],upload:async(parent,name,blob)=>{assert.ok(blob.size>1000);writes.push(['pdf',parent]);return {id:'pdf1',name};},writeJson:async(parent,name,value)=>{writes.push(['json',parent,value]);}};const logo='data:image/png;base64,'+(await readFile(new URL('../assets/logo.png',import.meta.url))).toString('base64');mountDepot({g:()=>g,projects:()=>[{id:'job',name:'2026-001172 ANTIN'}],run:fn=>fn(),authorize:async()=>authorized++,logo:async()=>logo,status:()=>{},download:()=>{}});document.getElementById('dproject').value='job';document.querySelector('[data-k=description]').value='Prise';document.querySelector('[data-k=quantity]').value='2';document.getElementById('dapprove').checked=true;await document.getElementById('dsave').onclick();assert.equal(authorized,1);assert.equal(writes[0][1],'job/03_COMMANDES/DEPOT_BUC');assert.equal(writes[1][2].projectId,'job');assert.equal(writes[1][2].state,'À préparer');assert.match(document.getElementById('dstatus').textContent,/enregistrés/);
 }finally{globalThis.document=oldDocument;globalThis.fetch=oldFetch;dom.window.close();}
});
