import test from 'node:test';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';import {openPayroll} from '../lib/payroll-sheet.js';
const data={people:[{id:'p',name:'Test',type:'internal',weeklyTarget:39,active:true}],events:[],interventions:[],visits:[],closures:[]};
test('draft saves incomplete review, export warning remains visible at buttons and stored hours stay net',async()=>{
 const dom=new JSDOM('<dialog id="modal"><div id="modalBody"></div></dialog>');const before=globalThis.document;globalThis.document=dom.window.document;let stored={},writes=0,downloads=0;
 try{const ui={role:()=> 'admin',data,repo:{load:async()=>structuredClone(stored),save:async(k,v)=>{stored=structuredClone(v);writes++;}},c:{modal:(t,html)=>document.getElementById('modalBody').innerHTML=html,download:()=>downloads++}};await openPayroll(ui,'2026-09');const select=document.getElementById('psPerson');select.value='p';await select.onchange();const input=document.querySelector('[data-day="0"] [data-k="hours"]');input.value='8';input.oninput();await document.getElementById('psSave').onclick();assert.equal(writes,1);assert.equal(stored.days[0].hours,8);assert.match(document.getElementById('psFeedback').textContent,/Fiche enregistrée/);await document.getElementById('psPdf').onclick();assert.equal(writes,2);assert.equal(downloads,0);assert.match(document.getElementById('psFeedback').textContent,/PDF non exporté.*2026-09-01/);assert.ok(document.getElementById('psFeedback').closest('.psFooter'));assert.equal(input.disabled,false);
 const button=document.querySelector('[data-standard="0"]');button.onclick();assert.match(document.querySelector('[data-day="0"] [data-k="note"]').value,/hors pause déjeuner/);
 }finally{globalThis.document=before;dom.window.close();}
});
test('failed save reports failure beside buttons without generating PDF',async()=>{const dom=new JSDOM('<div id="modalBody"></div>'),before=globalThis.document;globalThis.document=dom.window.document;let downloads=0;try{await openPayroll({role:()=> 'admin',data,repo:{load:async()=>({}),save:async()=>{throw Error('Microsoft indisponible');}},c:{modal:(t,h)=>document.getElementById('modalBody').innerHTML=h,download:()=>downloads++}},'2026-09');const s=document.getElementById('psPerson');s.value='p';await s.onchange();await document.getElementById('psPdf').onclick();assert.match(document.getElementById('psFeedback').textContent,/Enregistrement non effectué.*Microsoft indisponible/);assert.equal(downloads,0);}finally{globalThis.document=before;dom.window.close();}});
