import test from 'node:test';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';
import {OpsUI} from '../lib/ops-ui.js';import {eventProjectIds} from '../lib/planning-affairs.js';import {payrollRows} from '../lib/workforce.js';import {progress} from '../lib/project-progress.js';import {projectPriority} from '../lib/project-field.js';
test('two affairs save one calendar block, preserve selection on edit, and count employee hours once',async()=>{
 const dom=new JSDOM('<div id="modal"></div>',{url:'https://opus.example'});globalThis.document=dom.window.document;globalThis.localStorage=dom.window.localStorage;let opened='';
 const u=new OpsUI({graph:{},getConfig:()=>({}),getUser:()=>({}),isAdmin:()=>true,toast(){},getCatalog:()=>({projects:[{id:'a',name:'2026-001194 UCPA'},{id:'b',name:'2026-000715 UCPA'}]}),openProject:id=>opened=id,projectMeta:async()=>({adresse:'Patinoire'}),modal:(t,h)=>document.getElementById('modal').innerHTML=h});
 document.getElementById('modal').close=()=>{};u.data={people:[{id:'r',name:'Roberto',active:true,weeklyTarget:39}],events:[],interventions:[],visits:[],closures:[]};u.save=async()=>{};u.saveWithFeedback=async(f,m,work)=>work();
 await u.planEvent();const select=document.getElementById('eventLink');select.value='project|a';select.dispatchEvent(new dom.window.Event('change'));document.querySelector('[data-linked-affair][value="b"]').checked=true;document.getElementById('eventGroupTitle').value='UCPA Patinoire';document.getElementById('eventInstructions').value='1194 le matin, 715 l’après-midi';document.getElementById('eventDate').value='2026-09-16';document.getElementById('toggleTeam').click();const person=document.querySelector('[name="teamPerson"]');person.checked=true;person.dispatchEvent(new dom.window.Event('change'));await document.getElementById('eventForm').onsubmit({preventDefault(){}});
 assert.equal(u.data.events.length,1);const e=u.data.events[0];assert.deepEqual(eventProjectIds(e),['a','b']);assert.match(e.title,/001194.*000715/);assert.equal(payrollRows(u.data,'2026-09').reduce((n,r)=>n+r.planned,0),8);
 for(const id of ['a','b']){assert.equal(progress(u.data,id).scheduled,true);assert.equal(progress(u.data,id).planned,0);assert.equal(projectPriority(u.data.events,id,new Date('2026-09-16T12:00:00')).today,true);}
 await u.openEvent(e.id);assert.equal(opened,'');assert.equal(document.querySelectorAll('[data-open-affair]').length,2);assert.match(document.getElementById('modal').textContent,/1194 le matin/);document.querySelector('[data-open-affair="b"]').click();assert.equal(opened,'b');
 await u.planEvent(e);assert.equal(document.querySelector('[data-linked-affair][value="b"]').checked,true);document.querySelector('[data-linked-affair][value="b"]').checked=false;await document.getElementById('eventForm').onsubmit({preventDefault(){}});assert.deepEqual(eventProjectIds(e),['a']);assert.equal(u.data.events.length,1);dom.window.close();
});
