import test from 'node:test';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';
import {OpsUI} from '../lib/ops-ui.js';import {bindReportAI,savedVisitReportSource} from '../lib/report-ai.js';import {editResource,manageClosures} from '../lib/workforce-ui.js';
function setup(){const dom=new JSDOM('<div id="modal"></div><main id="calendarPage"></main>',{url:'https://opus.example'});for(const k of ['document','window','localStorage','Event'])globalThis[k]=dom.window[k];globalThis.confirm=()=>true;const ctx={getUser:()=>({displayName:'Admin'}),getConfig:()=>({}),isAdmin:()=>true,graph:{},toast(){},modal(title,html){document.getElementById('modal').innerHTML=html;},getCatalog:()=>({projects:[]})};const ui=new OpsUI(ctx);ui.data={clients:[],people:[{id:'p',name:'Test',active:true,type:'internal',weeklyTarget:39,absences:[{start:'2026-09-14',end:'2026-09-15',type:'maladie',label:'Maladie'}]}],events:[],visits:[],interventions:[],closures:[{start:'2026-12-24',end:'2026-12-31',label:'Noël'}]};return ui;}
test('calendar has grey absence, red closure, blocked team and schedule guard',async()=>{const ui=setup();assert.match(ui.dayColumn(new Date('2026-09-14T12:00:00')),/opusAbsent/);assert.match(ui.dayColumn(new Date('2026-12-25T12:00:00')),/opusClosed/);assert.match(ui.teamPickerHtml([],'2026-09-14'),/disabled/);assert.throws(()=>ui.validateScheduling('2026-09-14','08:00','10:00',['p']),/indisponible|Maladie/);assert.throws(()=>ui.validateScheduling('2026-12-25','08:00','10:00',[]),/fermée/);await ui.renderCalendar();assert.match(document.body.textContent,/Fermetures entreprise/);});
test('resource form cancellation does not mutate absences; admin-managed defaults survive refresh',async()=>{const ui=setup();editResource(ui,ui.data.people[0]);document.getElementById('wrAddAbsence').click();assert.equal(ui.data.people[0].absences.length,1);ui.c.getConfig=()=>({defaultPeople:[{id:'p',name:'Test',weeklyTarget:35}]});ui.data.people[0].officeManaged=true;await ui.syncDefaultPeople();assert.equal(ui.data.people[0].weeklyTarget,39);});
test('visit report uses all written tasks, rejects stale AI response and preserves raw notes',async()=>{const ui=setup(),v={id:'v',summary:'La prise non funziona',notes:'à vérifier',visitTasks:[{room:'Cuisine',need:'sostituire presa',length:'2',photos:['private']}],needsQuote:true};ui.c.modal('',`<form id="finishVisit"><textarea id="vSummary">${v.summary}</textarea><textarea id="vNotes">${v.notes}</textarea><select id="vNeedsQuote"><option value="oui">Oui</option></select><div class="actionRow"><button id="downloadVisitPdf" type="button">PDF</button><button id="saveVisitPdf" type="button">Archiver</button><button type="submit">Enregistrer</button></div></form>`);let resolve;ui.assistant.request=async(action,text)=>{assert.equal(action,'visit_report_fr');assert.match(text,/sostituire/);assert.doesNotMatch(text,/private|photos/);return new Promise(r=>resolve=r);};bindReportAI(ui,v,true,true);const b=document.getElementById('generateClientReport');let call=b.onclick();document.getElementById('vNotes').value='notes modifiées';resolve({text:'stale'});await call;assert.equal(document.getElementById('clientReportDraft').value,'');call=b.onclick();resolve({text:'La prise ne fonctionne pas. Remplacement à chiffrer.'});await call;document.getElementById('approveClientReport').checked=true;document.getElementById('finishVisit').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));assert.equal(v.clientReportApproved,true);assert.equal(v.summary,'La prise non funziona');assert.match(v.clientReport,/chiffrer/);document.getElementById('vNotes').value='autre';const e=new Event('submit',{bubbles:true,cancelable:true});document.getElementById('finishVisit').dispatchEvent(e);assert.equal(e.defaultPrevented,true);});
test('technician cannot open company closure editor',()=>{const ui=setup();ui.c.isAdmin=()=>false;manageClosures(ui);assert.equal(document.getElementById('closuresForm'),null);});

test('real visit with an existing task renders and generates its French report before the footer',async()=>{const ui=setup();const v={id:'visit-real',number:'VIS-TEST',type:'Visite avant devis',summary:'Tableau à vérifier',notes:'accès mardi',status:'planifiee',visitTasks:[{room:'Cuisine',need:'sostituire presa',photos:[]}],photos:[]};ui.data.visits=[v];ui.assistant.request=async(action,text)=>{assert.equal(action,'visit_report_fr');assert.match(text,/sostituire presa/);return {text:'Cuisine : remplacement de la prise à prévoir.'};};await ui.openVisit(v.id);const form=document.getElementById('finishVisit'),button=document.getElementById('generateClientReport');assert.ok(button);assert.equal(button.closest('section').parentElement,form);assert.ok(form.querySelector('[data-edit-visit-task]'));assert.ok(form.classList.contains('simpleReport'));assert.equal(document.getElementById('vSummary').closest('details'),null);assert.equal(document.getElementById('visitPhotoPreview').closest('details'),null);assert.ok(form.querySelector('[data-edit-visit-task]').closest('details').open);assert.equal(document.getElementById('vNotes').value,'accès mardi');await button.onclick();assert.match(document.getElementById('clientReportDraft').value,/Cuisine/);});
test('only admin can delete visits; cancellation and failures preserve them',async()=>{
 const ui=setup();document.body.insertAdjacentHTML('beforeend','<main id="visitsPage"></main>');
 const v={id:'v-delete',number:'VIS-001',clientName:'Test',visitTasks:[],photos:[]};ui.data.visits=[v];ui.data.events=[{id:'linked',kind:'visit',linkId:v.id},{id:'other',kind:'intervention',linkId:v.id}];
 let saves=[];ui.save=async key=>{saves.push(key);};ui.renderCalendar=async()=>{};
 ui.c.isAdmin=()=>false;ui.role=()=> 'manager';await ui.renderVisits();assert.equal(document.querySelector('[data-delete-visit]'),null);await ui.openVisit(v.id);assert.equal(document.getElementById('deleteVisitReport'),null);await ui.deleteVisit(v.id);assert.equal(saves.length,0);assert.equal(ui.data.visits.length,1);
 ui.c.isAdmin=()=>true;await ui.renderVisits();assert.ok(document.querySelector('[data-delete-visit]'));globalThis.confirm=()=>false;await ui.deleteVisit(v.id);assert.equal(ui.data.visits.length,1);assert.equal(saves.length,0);
 globalThis.confirm=()=>true;ui.save=async()=>{throw new Error('offline');};await ui.deleteVisit(v.id);assert.equal(ui.data.visits.length,1);assert.equal(ui.data.events.length,2);
 ui.save=async key=>saves.push(key);await ui.deleteVisit(v.id);assert.deepEqual(saves,['visits','events']);assert.equal(ui.data.visits.length,0);assert.deepEqual(ui.data.events.map(e=>e.id),['other']);
});
test('project equipment report persists per-cabinet times, phases and quote flag',async()=>{
 const ui=setup();ui.data.interventions=[{id:'equipment-report',number:'INT-TEST',projectId:'proj',reportItems:[{id:'cab',title:'Armoire 1',photos:[],phasePhotos:{before:[{dataUrl:'data:image/jpeg;base64,AA',name:'avant'}],during:[],after:[]}}],photos:[]}];let saved;ui.save=async()=>{saved=structuredClone(ui.data.interventions[0]);};ui.saveWithFeedback=async(form,msg,work)=>work();
 await ui.openIntervention('equipment-report');assert.ok(document.getElementById('batchEquipment'));await ui.editInterventionItem('equipment-report',0);
 assert.ok(document.getElementById('eqCam_before'));assert.ok(document.getElementById('eqCam_during'));assert.ok(document.getElementById('eqCam_after'));
 document.getElementById('equipmentStart').value='2026-09-14T08:00';document.getElementById('equipmentEnd').value='2026-09-14T09:00';document.getElementById('iiObs').value='Poignée cassée';document.getElementById('iiQuote').value='oui';await document.getElementById('intItemForm').onsubmit({preventDefault(){}});
 assert.equal(saved.reportItems[0].needsQuote,true);assert.equal(saved.reportItems[0].phasePhotos.before.length,1);assert.ok(saved.reportItems[0].startedAt);assert.ok(saved.reportItems[0].endedAt);assert.equal(saved.reportItems[0].observation,'Poignée cassée');
});
test('project report creation links the existing project and equipment batch creates no performed work',async()=>{
 const ui=setup();let saved=0;ui.save=async()=>saved++;const p={id:'proj',name:'001194 — Test'};await ui.openProjectReports(p,{devis:'001194',client:'Client test',adresse:'Adresse test'});await document.getElementById('newProjectReport').onclick({currentTarget:document.getElementById('newProjectReport')});const x=ui.data.interventions[0];assert.equal(x.projectId,p.id);assert.equal(saved,1);document.getElementById('batchEquipment').click();ui.saveWithFeedback=async(f,m,work)=>work();await document.getElementById('equipmentBatch').onsubmit({preventDefault(){}});assert.equal(x.reportItems.length,14);assert.equal(x.reportItems[13].title,'Armoire 14');assert.ok(x.reportItems.every(i=>!i.startedAt&&!i.endedAt&&!i.action));
});
test('project PDF archive goes under the existing project while standalone intervention keeps its folder',async()=>{const ui=setup(),paths=[];ui.interventionPdf=async()=>new Blob(['pdf']);ui.save=async()=>{};ui.c.graph={folder:async(parent,name)=>{paths.push([parent,name]);return{id:parent+'/'+name};},base:id=>id,request:async()=>{},writeJson:async()=>{}};await ui.saveInterventionPackage({projectId:'project-id',projectName:'001194',number:'INT-T',reportItems:[]});assert.deepEqual(paths.slice(0,2),[['project-id','05_PDF_GENERES'],['project-id/05_PDF_GENERES','COMPTES_RENDUS']]);paths.length=0;await ui.saveInterventionPackage({number:'INT-S',reportItems:[]});assert.deepEqual(paths[0],['root','INTERVENTIONS']);});
test('saving appointment schedules assigned team automatically with no actual hours; resave does not duplicate',async()=>{
 const ui=setup();ui.saveWithFeedback=async(f,m,work)=>work();ui.save=async()=>{};ui.resolveClientChoice=async()=>({client:{id:'client',name:'Client'},site:{id:'site',address:'Paris'}});await ui.editIntervention();document.getElementById('iSiteAddress').value='Paris';document.getElementById('iTitle').value='Dépannage';document.getElementById('iStart').value='2026-09-16T10:00';document.getElementById('iStart').onchange();assert.equal(document.getElementById('iEnd').value,'2026-09-16T11:00');document.querySelector('[name=teamPerson]').checked=true;await document.getElementById('intForm').onsubmit({preventDefault(){}});const x=ui.data.interventions[0];assert.equal(x.status,'planifiee');assert.deepEqual(x.teamIds,['p']);assert.equal(x.actualStart,undefined);assert.equal(x.actualEnd,undefined);assert.equal(ui.data.events.length,1);assert.deepEqual(ui.data.events[0].teamIds,['p']);await ui.upsertLinkedEvent('intervention',x);assert.equal(ui.data.events.length,1);x.plannedStart='';x.plannedEnd='';await ui.upsertLinkedEvent('intervention',x);assert.equal(ui.data.events.length,0);
});
