import test from 'node:test';
import assert from 'node:assert/strict';
import {PrivateCalendar,privateEvents,editPrivateEvent} from '../lib/private-calendar.js';
import {calendarEvents} from '../lib/planning-reassign.js';
import {JSDOM} from 'jsdom';
function fixture(){let stored=[],calls=[];const g={request:async(path,opts)=>{calls.push([path,opts]);if(path.endsWith('/approot'))return {id:'root'};if(opts?.method==='PUT'){const row=JSON.parse(await opts.body.text());stored=[row];return {id:'file',eTag:'v2'};}if(opts?.method==='DELETE')return null;return {'@microsoft.graph.downloadUrl':'https://download.test/private',eTag:'v1'};},all:async()=>stored.map(r=>({id:'file',name:'opus-private-appointment-'+r.id+'.json'})),fetcher:async()=>({ok:true,json:async()=>stored[0]})};return {repo:new PrivateCalendar(g,'owner'),calls,setRows:r=>stored=r};}
test('private storage only uses own drive, requires successful load and validates range',async()=>{const {repo,calls}=fixture();const x={title:'Commercial',start:'2026-09-29T10:00:00Z',end:'2026-09-29T11:00:00Z'};await assert.rejects(repo.save(x));await repo.load();await assert.rejects(repo.save({...x,end:x.start}));await repo.save(x);assert.equal(repo.rows[0].ownerId,'owner');assert.equal(repo.rows[0].kind,'private');assert.ok(calls.every(([p])=>p.startsWith('/me/drive/')));const id=repo.rows[0].id;await repo.save({...x,id});assert.equal(calls.at(-1)[1].headers['If-Match'],'v2');await repo.remove(id);assert.equal(repo.rows.length,0);});
test('private events never enter shared array, staff or another owner calendar',()=>{const rows=[{id:'mine',ownerId:'owner'},{id:'other',ownerId:'else'}];const ui={c:{isAdmin:()=>true},user:{id:'owner'},privateCalendar:{ready:true,rows},data:{events:[{id:'public',teamIds:[]}]}};assert.deepEqual(calendarEvents(ui).map(x=>x.id),['public','mine']);assert.equal(ui.data.events.length,1);ui.c.isAdmin=()=>false;assert.equal(privateEvents(ui).length,0);assert.deepEqual(calendarEvents(ui).map(x=>x.id),['public']);ui.c.isAdmin=()=>true;ui.user.id='unknown';assert.equal(privateEvents(ui).length,0);});
test('unreadable or wrong-owner documents fail closed and cannot be overwritten',async()=>{const {repo,setRows}=fixture();setRows([{id:'i',kind:'private',ownerId:'else'}]);await assert.rejects(repo.load());assert.equal(repo.ready,false);await assert.rejects(repo.save({title:'x'}));});
test('whole-day form persists an exclusive end and no shared booking',async()=>{const dom=new JSDOM('<div id="modal"></div>',{url:'https://opus.test'});globalThis.document=dom.window.document;let saved;const ui={c:{isAdmin:()=>true,modal:(_,h)=>document.getElementById('modal').innerHTML=h},privateCalendar:{ready:true,save:async x=>saved=x},localDT:d=>d.slice(0,16),renderCalendar:async()=>{}};document.getElementById('modal').close=()=>{};editPrivateEvent(ui);document.getElementById('peTitle').value='Journée libre';document.getElementById('peAllDay').checked=true;document.getElementById('peAllDay').onchange();document.getElementById('peStart').value='2026-09-29';document.getElementById('peEnd').value='2026-09-29';await document.getElementById('privateEventForm').onsubmit({preventDefault(){}});assert.equal(saved.allDay,true);assert.equal((saved.end-saved.start)/3600000,24);dom.window.close();});
