import test from 'node:test';
import assert from 'node:assert/strict';
import {PrivateCalendar,privateEvents,editPrivateEvent} from '../lib/private-calendar.js';
import {calendarEvents} from '../lib/planning-reassign.js';
import {JSDOM} from 'jsdom';
function fixture(){let stored=[],calls=[];const g={request:async(path,opts)=>{calls.push([path,opts]);if(path.endsWith('/approot'))return {id:'root'};if(opts?.method==='PUT'){const row=JSON.parse(await opts.body.text());stored=[row];return {id:'file',eTag:'v2'};}if(opts?.method==='DELETE')return null;return {'@microsoft.graph.downloadUrl':'https://download.test/private',eTag:'v1'};},all:async()=>stored.map(r=>({id:'file',name:'opus-private-appointment-'+r.id+'.json'})),fetcher:async()=>({ok:true,json:async()=>stored[0]})};return {repo:new PrivateCalendar(g,'owner'),calls,setRows:r=>stored=r};}
test('private storage only uses own drive, requires successful load and validates range',async()=>{const {repo,calls}=fixture();const x={title:'Commercial',start:'2026-09-29T10:00:00Z',end:'2026-09-29T11:00:00Z'};await assert.rejects(repo.save(x));await repo.load();await assert.rejects(repo.save({...x,end:x.start}));await repo.save(x);assert.equal(repo.rows[0].ownerId,'owner');assert.equal(repo.rows[0].kind,'private');assert.ok(calls.every(([p])=>p.startsWith('/me/drive/')));const id=repo.rows[0].id;await repo.save({...x,id});assert.equal(calls.at(-1)[1].headers['If-Match'],'v2');await repo.remove(id);assert.equal(repo.rows.length,0);});
test('private events never enter shared array, staff or another owner calendar',()=>{const rows=[{id:'mine',ownerId:'owner'},{id:'other',ownerId:'else'}];const ui={c:{isAdmin:()=>true},user:{id:'owner'},privateCalendar:{ready:true,rows},data:{events:[{id:'public',teamIds:[]}]}};assert.deepEqual(calendarEvents(ui).map(x=>x.id),['public','mine']);assert.equal(ui.data.events.length,1);ui.c.isAdmin=()=>false;assert.equal(privateEvents(ui).length,0);assert.deepEqual(calendarEvents(ui).map(x=>x.id),['public']);ui.c.isAdmin=()=>true;ui.user.id='unknown';assert.equal(privateEvents(ui).length,0);});
test('unreadable or wrong-owner documents fail closed and cannot be overwritten',async()=>{const {repo,setRows}=fixture();setRows([{id:'i',kind:'private',ownerId:'else'}]);await assert.rejects(repo.load());assert.equal(repo.ready,false);await assert.rejects(repo.save({title:'x'}));});
test('whole-day form persists an exclusive end and no shared booking',async()=>{const dom=new JSDOM('<div id="modal"></div>',{url:'https://opus.test'});globalThis.document=dom.window.document;let saved;const ui={c:{isAdmin:()=>true,modal:(_,h)=>document.getElementById('modal').innerHTML=h},privateCalendar:{ready:true,save:async x=>saved=x},localDT:d=>d.slice(0,16),renderCalendar:async()=>{}};document.getElementById('modal').close=()=>{};editPrivateEvent(ui);document.getElementById('peTitle').value='Journée libre';document.getElementById('peAllDay').checked=true;document.getElementById('peAllDay').onchange();document.getElementById('peStart').value='2026-09-29';document.getElementById('peEnd').value='2026-09-29';await document.getElementById('privateEventForm').onsubmit({preventDefault(){}});assert.equal(saved.allDay,true);assert.equal((saved.end-saved.start)/3600000,24);dom.window.close();});

test('own personnel filter includes existing private bookings, without changing team or hours',()=>{
 const row={id:'private',ownerId:'owner',kind:'private',teamIds:[],exactHours:true};
 const ui={c:{isAdmin:()=>true},user:{id:'owner',displayName:'Ignazio Carbonaro',mail:'ignazio@opuselec.fr'},privateCalendar:{ready:true,rows:[row]},calendarPersonId:'ignazio',data:{people:[{id:'ignazio',name:'CARBONARO Ignazio',email:''},{id:'roberto',name:'CARBONARO Roberto'}],events:[{id:'work',teamIds:['ignazio']},{id:'other',teamIds:['roberto']}]}};
 assert.deepEqual(calendarEvents(ui).map(e=>e.id),['work','private']);assert.deepEqual(row.teamIds,[]);assert.equal(ui.data.events.length,2);
 ui.calendarPersonId='roberto';assert.deepEqual(calendarEvents(ui).map(e=>e.id),['other']);
 ui.calendarPersonId='ignazio';ui.c.isAdmin=()=>false;assert.deepEqual(calendarEvents(ui).map(e=>e.id),['work']);
 ui.c.isAdmin=()=>true;ui.user.displayName='Different display name';ui.data.people[0].email='IGNAZIO@OPUSELEC.FR';assert.deepEqual(calendarEvents(ui).map(e=>e.id),['work','private']);
 ui.data.people[0].email='';assert.deepEqual(calendarEvents(ui).map(e=>e.id),['work']);
});

test('explicit account-owned association survives reload and ignores mismatched names and emails',async()=>{
 let settings=null;const g={request:async(p,o)=>{if(o?.method==='PUT'){settings=JSON.parse(await o.body.text());return {};}if(p.endsWith('/approot'))return {id:'root'};return {'@microsoft.graph.downloadUrl':'https://example.test/settings'};},all:async()=>settings?[{id:'settings',name:'opus-private-calendar-settings.json'}]:[],fetcher:async()=>({ok:true,json:async()=>settings})};
 const repo=new PrivateCalendar(g,'owner');await repo.load();await repo.associatePerson('p1');const otherDevice=new PrivateCalendar(g,'owner');await otherDevice.load();assert.equal(otherDevice.personId,'p1');
 otherDevice.rows=[{id:'private',ownerId:'owner'}];const ui={c:{isAdmin:()=>true},user:{id:'owner',displayName:'Account alias'},data:{people:[{id:'p1',name:'CARBONARO Ignazio'}],events:[]},calendarPersonId:'p1',privateCalendar:otherDevice};assert.equal(calendarEvents(ui).length,1);ui.c.isAdmin=()=>false;assert.equal(calendarEvents(ui).length,0);
 const unauthorized=new PrivateCalendar(g,'different');await assert.rejects(unauthorized.load());assert.equal(unauthorized.ready,false);
});
test('failed association save does not change the prior mapping',async()=>{const repo=new PrivateCalendar({request:async()=>{throw Error('offline');}},'owner');repo.ready=true;repo.personId='old';await assert.rejects(repo.associatePerson('new'));assert.equal(repo.personId,'old');});

test('weekly recurrence keeps local times through daylight saving and inclusive final date',async()=>{
 const {expandPrivateEvents}=await import('../lib/private-calendar.js');const tz=process.env.TZ;process.env.TZ='Europe/Paris';
 try{const rows=expandPrivateEvents([{id:'school',ownerId:'owner',start:new Date('2026-10-19T08:20:00').toISOString(),end:new Date('2026-10-19T08:50:00').toISOString(),recurrence:{days:[1,2,4,5],until:'2026-10-30'}}]);assert.equal(rows.length,8);assert.ok(rows.every(r=>new Date(r.start).getHours()===8&&new Date(r.start).getMinutes()===20));assert.ok(rows.every(r=>new Date(r.end)-new Date(r.start)===1800000));assert.equal(new Set(rows.map(r=>r.id)).size,8);assert.ok(rows.every(r=>r.seriesId==='school'));assert.equal(new Date(rows.at(-1).start).getDate(),30);}finally{if(tz===undefined)delete process.env.TZ;else process.env.TZ=tz;}
});
test('weekly save is one private document; edits replace its rule; invalid empty series rejected',async()=>{
 const {repo}=fixture();await repo.load();const input={title:'Réunion',start:'2026-09-28T10:00:00',end:'2026-09-28T11:00:00',recurrence:{days:[1],until:'2026-10-31'}};await repo.save(input);assert.equal(repo.rows.length,1);assert.deepEqual(repo.rows[0].recurrence.days,[1]);const id=repo.rows[0].id;await repo.save({...input,id,recurrence:{days:[2],until:'2026-10-31'}});assert.equal(repo.rows.length,1);assert.deepEqual(repo.rows[0].recurrence.days,[2]);await assert.rejects(repo.save({...input,recurrence:{days:[],until:'2026-10-31'}}));await assert.rejects(repo.save({...input,recurrence:{days:[3],until:'2026-09-28'}}));await assert.rejects(repo.save({...input,recurrence:{days:[1],until:'2040-01-01'}}));
});
