import test from 'node:test';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';
import {visitStage,mountVisitTabs} from '../lib/visit-followup.js';import {openReception} from '../lib/reception.js';
const type='Réception de chantier / intervention';
test('Existing completed receptions are classified separately from visits and quotes',()=>{
 assert.equal(visitStage({type,status:'terminee'}),'receptionsDone');assert.equal(visitStage({type,status:'terminee',quoteNumber:'old'}),'receptionsDone');assert.equal(visitStage({type,status:'planifiee'}),'active');assert.equal(visitStage({status:'terminee'}),'finished');assert.equal(visitStage({status:'terminee',quoteNumber:'D1'}),'quoted');
});
test('Tabs hide completed receptions from finished visits and preserve access in their own tab',()=>{
 const rows=[{type,status:'terminee'},{status:'terminee'},{type,status:'planifiee'}];const dom=new JSDOM('<main><div class="projectList">'+rows.map(()=>'<article class="projectCard"><h3>Client</h3><div class="actionRow"></div></article>').join('')+'</div></main>');globalThis.document=dom.window.document;const ui={c:{isAdmin:()=>false},visitView:'finished'};mountVisitTabs(ui,document.querySelector('main'),rows);const cards=[...document.querySelectorAll('.projectCard')];assert.deepEqual(cards.map(c=>c.hidden),[true,false,true]);const tab=document.querySelector('[data-stage=receptionsDone]');assert.match(tab.textContent,/Réceptions effectuées \(1\)/);tab.click();assert.deepEqual(cards.map(c=>c.hidden),[false,true,true]);assert.equal(tab.getAttribute('aria-pressed'),'true');dom.window.close();
});
test('Confirming completion closes the window and opens the completed reception tab only after save',async()=>{
 const dom=new JSDOM('<dialog id="modal"></dialog>');globalThis.document=dom.window.document;let closed=false,rendered=false;const modal=document.getElementById('modal');modal.close=()=>{closed=true;};const v={id:'r',type,status:'planifiee',notes:'Avant',attachments:[]};const ui={c:{modal:(title,html)=>modal.innerHTML=html,toast:()=>{}},canPlan:()=>true,teamNames:()=>'',save:async()=>{},renderVisits:async()=>{rendered=true;assert.equal(ui.visitView,'receptionsDone');}};openReception(ui,v);document.getElementById('rNotes').value='Réserve conservée';await document.getElementById('rDone').onclick({currentTarget:document.getElementById('rDone')});assert.equal(v.status,'terminee');assert.equal(v.notes,'Réserve conservée');assert.equal(closed,true);assert.equal(rendered,true);
 closed=false;rendered=false;v.status='planifiee';ui.visitView='active';ui.save=async()=>{throw Error('Enregistrement impossible');};openReception(ui,v);await document.getElementById('rDone').onclick({currentTarget:document.getElementById('rDone')});assert.equal(closed,false);assert.equal(rendered,false);assert.equal(v.status,'planifiee');assert.equal(ui.visitView,'active');dom.window.close();
});
