import test from 'node:test';import assert from 'node:assert/strict';
import {WarmCache,OPS_KEYS} from '../lib/warm-cache.js';import {Graph} from '../lib/cloud.js';import {PrivateCalendar} from '../lib/private-calendar.js';
const operations=()=>Object.fromEntries(OPS_KEYS.map(k=>[k,[]]));
function setup(){const data=new Map();const store={get:async k=>structuredClone(data.get(k)),set:async(k,v)=>data.set(k,structuredClone(v))};const cfg={clientId:'app',siteHost:'tenant',sitePath:'/sites/opus'};return {store,cfg,cache:new WarmCache(store,'account-a',cfg)};}
const snapshot=()=>({user:{id:'u'},drive:{id:'drive'},catalog:{projects:[],categories:[],loose:[]},operations:operations()});
test('Complete snapshots are isolated by account and library; incomplete snapshots are ignored',async()=>{const {cache,store,cfg}=setup();await cache.write(snapshot());assert.ok(await cache.read());assert.equal(await new WarmCache(store,'account-b',cfg).read(),null);assert.equal(await new WarmCache(store,'account-a',{...cfg,sitePath:'/other'}).read(),null);await cache.write({operations:{events:[]}});assert.equal(await cache.read(),null);});
test('Only confirmed collections update and simultaneous saves are retained',async()=>{const {cache}=setup();await cache.write(snapshot());const rows=[{id:'client'}];await Promise.all([cache.savedKind('clients',rows),cache.savedKind('events',[{id:'event'}])]);rows[0].id='unsaved';const saved=await cache.read();assert.equal(saved.operations.clients[0].id,'client');assert.equal(saved.operations.events[0].id,'event');});
test('Private appointments cannot be restored into another account or owner',async()=>{const {cache,store,cfg}=setup();await cache.privateWrite({ownerId:'owner',rows:[{ownerId:'owner',id:'private'}],personId:'p'});assert.equal((await cache.privateRead('owner')).rows.length,1);assert.equal(await cache.privateRead('worker'),null);assert.equal(await new WarmCache(store,'account-b',cfg).privateRead('owner'),null);});
test('Cached shared state rejects cloud mutations before token access',async()=>{let calls=0;const graph=new Graph(async()=>{calls++;return 'token';});graph.readOnlyCache=true;await assert.rejects(graph.request('/test',{method:'PUT',body:[]}),/mémorisées/);assert.equal(calls,0);});
test('Cached private state rejects all writes and preserves records',async()=>{const c=new PrivateCalendar({request:()=>assert.fail('No remote call')},'owner');c.cacheMode=true;c.ready=true;c.rows=[{id:'one',ownerId:'owner'}];await assert.rejects(c.save({title:'New'}),/mémorisé/);await assert.rejects(c.remove('one'),/mémorisé/);await assert.rejects(c.associatePerson('p'),/mémorisé/);assert.equal(c.rows.length,1);});
