import {TYPES,SOURCES,VERSION,route,requirements,pieceState,blockers,safe} from './enedis-rules.js';
async function bytes(url){const r=await fetch(url);if(!r.ok)throw Error('Document indisponible : reconnectez-vous et rechargez.');return new Uint8Array(await r.arrayBuffer());}
export async function dossierPdf(d,mode='dossier'){
 const {jsPDF}=await import('../vendor/jspdf.js');const{installPdfFonts}=await import('./pdf-fonts.js');const p=new jsPDF();await installPdfFonts(p);const logo=await bytes(new URL('../assets/logo.png',import.meta.url));let y=48;
 const title=mode==='relance'?'PIÈCES À COMPLÉTER':mode==='courrier'?'COURRIER D’ACCOMPAGNEMENT':'DOSSIER DE RACCORDEMENT';
 const header=()=>{p.setFillColor(12,64,105);p.rect(0,0,210,3,'F');p.addImage(logo,'PNG',16,13,53,14.4);p.setFont('OpusSans','bold');p.setFontSize(11);p.setTextColor(12,64,105);p.text(title,194,20,{align:'right'});p.setFontSize(9);p.text(d.number,194,27,{align:'right'});p.setDrawColor(210,222,230);p.line(16,38,194,38);};header();
 const ensure=h=>{if(y+h>275){p.addPage();header();y=48;}};
 const text=(s,size=10,bold=false)=>{p.setFont('OpusSans',bold?'bold':'normal');p.setFontSize(size);p.setTextColor(35,49,63);for(const line of p.splitTextToSize(String(s||'Non renseigné'),176)){ensure(6);p.text(line,16,y);y+=size*.48;}y+=3;};
 const section=s=>{ensure(23);p.setFillColor(236,243,248);p.roundedRect(16,y-4,178,9,2,2,'F');text(s,10,true);y+=3;};
 text(d.company||'OPUS ELEC',12,true);text([d.companyAddress,d.companySiret&&'SIRET : '+d.companySiret,d.companyEmail,d.companyPhone].filter(Boolean).join(' · '),8);
 section('CLIENT ET PROJET');text(d.client,12,true);text([d.address,d.zip,d.city].filter(Boolean).join(' '));text(TYPES[d.type]);text('Référence Enedis : '+(d.enedisRef||'À attribuer'));text('Contact : '+[d.contact,d.email,d.phone].filter(Boolean).join(' · '));
 if(mode==='relance'){section('PIÈCES ET INFORMATIONS À COMPLÉTER');const b=blockers(d);text(b.length?'Merci de compléter les éléments suivants pour poursuivre la préparation du dossier.':'Aucun manque détecté par la liste de contrôle actuelle.');for(const x of b)text('• '+x);}
 else if(mode==='courrier'){section('À L’ATTENTION DU SERVICE CHARGÉ DE LA DEMANDE');text(route(d));text('Madame, Monsieur,');text('Veuillez trouver les éléments préparés pour le projet suivant : '+d.description);text('Échéance souhaitée : '+(d.wanted||'À préciser')+'. Puissance demandée : '+(d.power||'À préciser')+' kVA.');text('Merci de nous indiquer la référence de suivi ainsi que les éventuels compléments nécessaires à l’instruction de cette demande.');text('Contact pour le suivi : '+[d.company,d.companyEmail,d.companyPhone].filter(Boolean).join(' · '));text('Nom, date et signature à compléter avant envoi.');}
 else{
 section('FICHE TECHNIQUE');for(const[k,l]of [['description','Description'],['pdl','PDL / PRM'],['currentPower','Puissance actuelle (kVA)'],['power','Puissance souhaitée (kVA)'],['phase','Alimentation souhaitée'],['cadastre','Référence cadastrale'],['meterPosition','Emplacement souhaité / distances'],['wanted','Date souhaitée'],['end','Fin du provisoire'],['lots','Lots, puissances et équipements'],['constraints','Accès, contraintes et travaux préparatoires']])if(d[k])text(l+' : '+d[k]);
 section('ORIENTATION ET SUIVI');text(route(d));text('Étape déclarée : '+d.status);text('Prochaine action : '+(d.nextAction||'À préciser'));text('Échéance de suivi : '+(d.nextDate||'À préciser'));if(d.notes)text(d.notes);
 }
 section('BORDEREAU DES PIÈCES');let prevStage='';for(const r of requirements(d).sort((a,b)=>['depot','travaux','service'].indexOf(a.stage)-['depot','travaux','service'].indexOf(b.stage))){if(r.stage!==prevStage){text({depot:'Dépôt initial',travaux:'Avant travaux',service:'Mise en service'}[r.stage],10,true);prevStage=r.stage;}text(r.label+' — '+pieceState(d,r),9,true);const fs=(d.attachments||[]).filter(a=>a.category===r.id);for(const f of fs)text('Fichier : '+f.name,8);if(d.pieces?.[r.id]?.note)text('Note : '+d.pieces[r.id].note,8);}
 if(mode==='dossier'){section('CONTRÔLE AVANT DÉPÔT');const b=blockers(d);text(b.length?b.length+' point(s) à compléter / vérifier.':'Liste de contrôle renseignée. La recevabilité reste à confirmer par Enedis.');for(const x of b)text('• '+x,9);text('Les pièces de travaux et de mise en service sont suivies séparément du dépôt initial. Ce document OPUS accompagne la demande officielle ; il ne remplace pas le formulaire ou la saisie exigée sur le portail.',9);
 section('SOURCES OFFICIELLES');text('Références vérifiées le '+VERSION+'. À reconsulter avant dépôt ; les demandes propres au projet priment.',8);for(const[s,u]of SOURCES){text(s,8,true);text(u,7);}}
 for(let i=1;i<=p.getNumberOfPages();i++){p.setPage(i);p.setDrawColor(210,222,230);p.line(16,282,194,282);p.setFont('OpusSans','normal');p.setFontSize(8);p.text((d.company||'OPUS ELEC')+' · '+d.number,16,290);p.text(i+' / '+p.getNumberOfPages(),194,290,{align:'right'});}return p.output('blob');
}
export async function mandatePdf(d){
 if(!d.client||!d.company||!d.companySiret||!d.representative||!d.representativeRole||!d.companyRepresentative||!d.companyRole||!d.address||!d.city||!d.zip||!d.clientAddress||!['simple','special'].includes(d.mandate))throw Error('Complétez les parties, leurs adresses, représentants et fonctions ainsi que le type de mandat. Pour un particulier, indiquez « En son nom propre » comme fonction.');
 if(d.clientType!=='particulier'&&!d.clientSiret)throw Error('SIRET du client à compléter.');
 const{PDFDocument,StandardFonts,rgb}=await import('./enedis-vendor/pdf-lib.js');const p=await PDFDocument.load(await bytes(new URL('../assets/enedis/mandat-officiel.pdf',import.meta.url)));const {default:fontkit}=await import('./enedis-vendor/fontkit.js');p.registerFontkit(fontkit);const f=p.getForm(),font=await p.embedFont(await bytes(new URL('../assets/OpusSans.ttf',import.meta.url)),{subset:false});
 const values={'Nom et prénom bénéficiaire particulier':d.clientType==='particulier'?d.client:'','Adresse bénéficiaire particulier':d.clientType==='particulier'?d.clientAddress:'','Nom et prénom bénéficiaire entreprise':d.clientType!=='particulier'?d.client:'','SIRET Bénéficaire':d.clientType!=='particulier'?d.clientSiret:'','Nom et prénom du représentant bénéficiaire':d.clientType!=='particulier'?d.representative:'','Nom et prénom du représentant de la société  bénéficiaire':d.clientType!=='particulier'?d.representative:'','fonciton représentant de la société bénéficiaire':d.clientType!=='particulier'?d.representativeRole:'','Nom et prénom mandataire entreprise':d.company,'SIRET mandataire':d.companySiret,'Nom et prénom du représentant de la société  mandataire':d.companyRepresentative,'fonciton représentant de la société mandataire':d.companyRole,'Adresse Site 1':d.address,'CP site 1':d.zip+' '+d.city,'Déf site 1':TYPES[d.type],'Nom Prénom mandant signature':d.representative,'Nom Prénom mandataire signature':d.companyRepresentative};
 for(const[k,v]of Object.entries(values)){const field=f.getTextField(k);const value=String(v||'');const width=field.acroField.getWidgets()[0].getRectangle().width-4;const size=Math.min(8,width/Math.max(1,font.widthOfTextAtSize(value,8))*8);if(size<5.5)throw Error('Texte trop long pour le mandat : '+k+'. Abrégez ce champ avant de générer.');field.setText(value);field.setFontSize(size);}
 for(const[name,options,selected]of [
 ['Group1',[['particulier',46.48,622.45],['societe',52.48,550.45],['collectivite',196.48,550.45]],d.clientType],
 ['Group définition mandataire',[['particulier',46.48,403.45],['societe',52.48,331.45],['collectivite',196.48,331.45]],'societe']]){
 f.removeField(f.getField(name));const g=f.createRadioGroup('OPUS_'+name);for(const[o,x,y]of options)g.addOptionToPage(o,p.getPage(1),{x,y,width:11.5,height:10,borderWidth:.5});g.select(selected);
 }
 // The source form has duplicate export values for these radios. Rebuild the widgets to keep a unique, editable selection.
 f.removeField(f.getField('Choix Mandat'));const choice=f.createRadioGroup('OPUS_Choix_mandat');for(const[o,y]of [['simple',712.78],['special',611.78]])choice.addOptionToPage(o,p.getPage(2),{x:38.86,y,width:12.75,height:13.5,borderWidth:.5});choice.select(d.mandate);
 for(const[name,ys]of [['Group genre 1',[604.45]],['Group genre mandataire',[386.45]]]){f.removeField(f.getField(name));const g=f.createRadioGroup('OPUS_'+name);g.addOptionToPage('Madame',p.getPage(1),{x:72.48,y:ys[0],width:11.5,height:10});g.addOptionToPage('Monsieur',p.getPage(1),{x:150.48,y:ys[0],width:11.5,height:10});}
 for(const[n,k]of [['Check Box1','signContracts'],['Check Box2','payFees'],['Check Box3','executeWorks'],['Check Box4','signCard']]){const c=f.getCheckBox(n);d.mandate==='special'&&d[k]===true?c.check():c.uncheck();}
 // L342-6 remains unselected: this application does not qualify a contractor for network works.
 f.getCheckBox('Check Box3').uncheck();
 // Source widgets lack page references; removeField can leave deleted references in page annotations.
 for(const page of p.getPages()){const annots=page.node.Annots();if(annots)for(let i=annots.size()-1;i>=0;i--)if(!p.context.lookup(annots.get(i)))annots.remove(i);}
 f.updateFieldAppearances(font);
 const logo=await p.embedPng(await bytes(new URL('../assets/logo.png',import.meta.url)));p.getPage(0).drawImage(logo,{x:420,y:795,width:115,height:31.2});
 
 return new Blob([await p.save({updateFieldAppearances:false})],{type:'application/pdf'});
}
// ZIP store method: no CDN, no server, UTF-8 filenames and CRC32 per entry.
export async function zipFiles(entries){let offset=0;const chunks=[],central=[];const enc=new TextEncoder();const crc=a=>{let c=0xffffffff;for(const b of a){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;};
 for(const[name,blob]of entries){const n=enc.encode(name),a=new Uint8Array(await blob.arrayBuffer()),c=crc(a),h=new Uint8Array(30),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,c,true);v.setUint32(18,a.length,true);v.setUint32(22,a.length,true);v.setUint16(26,n.length,true);chunks.push(h,n,a);const ch=new Uint8Array(46),cv=new DataView(ch.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x800,true);cv.setUint32(16,c,true);cv.setUint32(20,a.length,true);cv.setUint32(24,a.length,true);cv.setUint16(28,n.length,true);cv.setUint32(42,offset,true);central.push(ch,n);offset+=h.length+n.length+a.length;}
 const size=central.reduce((s,a)=>s+a.length,0),end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,entries.length,true);v.setUint16(10,entries.length,true);v.setUint32(12,size,true);v.setUint32(16,offset,true);return new Blob([...chunks,...central,end],{type:'application/zip'});
}
