const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const MATERIAL_UNITS=['U','m','lot','boîte'];
export function validateMaterials(rows){for(const r of rows){if(!r.description.trim()||!/^\d+(?:[.,]\d+)?$/.test(String(r.quantity))||Number(String(r.quantity).replace(',','.'))<=0||!MATERIAL_UNITS.includes(r.unit))throw Error('Matériel : renseignez une désignation, une quantité positive et une unité sur chaque ligne.');}return rows;}
export function readMaterials(){const root=document.getElementById('requestMaterials');if(!root)return null;return [...root.querySelectorAll('tbody tr')].map(tr=>Object.fromEntries([...tr.querySelectorAll('[data-material]')].map(el=>[el.dataset.material,el.value.trim()]))).filter(r=>r.reference||r.description||r.quantity);}
export function materialText(rows=[]){return rows.map(r=>[r.reference,r.description,`${r.quantity} ${r.unit}`].filter(Boolean).join(' · ')).join('\n');}
export function drawMaterialTable(pdf,rows,layout){
 const widths=[31,91,25,25],xs=[16,49,142,169];
 const header=()=>{layout.ensure(15);let y=layout.getY();pdf.setFillColor(12,64,105);pdf.rect(16,y-3,178,9,'F');pdf.setTextColor(255);pdf.setFont('OpusSans','bold');pdf.setFontSize(8);['Référence','Description','Quantité','Unité'].forEach((s,i)=>pdf.text(s,xs[i]+1,y+3));layout.setY(y+12);};header();
 for(const row of rows){pdf.setFont('OpusSans','normal');pdf.setFontSize(8);const cols=[row.reference||'—',row.description,row.quantity,row.unit].map((s,i)=>pdf.splitTextToSize(String(s),widths[i]-3));for(let n=0;n<Math.max(...cols.map(c=>c.length));n++){if(layout.getY()+5>276){layout.ensure(15);header();}pdf.setFont('OpusSans','normal');pdf.setFontSize(8);pdf.setTextColor(35,48,59);cols.forEach((c,i)=>{if(c[n])pdf.text(c[n],xs[i]+1,layout.getY());});layout.setY(layout.getY()+4.5);}pdf.setDrawColor(210,222,230);pdf.line(16,layout.getY(),194,layout.getY());layout.setY(layout.getY()+5);}
}
export function mountMaterials(ui,x){if(!x.projectId)return;const section=document.querySelector('.projectReportSummary');if(!section)return;
 const box=document.createElement('div');box.id='requestMaterials';box.innerHTML='<h3>Liste du matériel à préparer</h3><p>Références facultatives. U = unité, m = mètre linéaire.</p><div class="materialRequestTable"><table><thead><tr><th>Référence</th><th>Description</th><th>Quantité</th><th>Unité</th><th></th></tr></thead><tbody></tbody></table></div><button type="button" id="addRequestMaterial" class="secondary">+ Matériel</button>';section.append(box);
 function row(v={}){const tr=document.createElement('tr');tr.innerHTML=`<td><input aria-label="Référence" data-material="reference" value="${esc(v.reference)}"></td><td><input aria-label="Description" data-material="description" placeholder="Prise, câble, gaine…" value="${esc(v.description)}"></td><td><input aria-label="Quantité" data-material="quantity" inputmode="decimal" value="${esc(v.quantity)}"></td><td><select aria-label="Unité" data-material="unit">${MATERIAL_UNITS.map(u=>`<option ${v.unit===u?'selected':''}>${u}</option>`).join('')}</select></td><td><button type="button" aria-label="Supprimer cette ligne">×</button></td>`;tr.querySelector('button').onclick=()=>tr.remove();box.querySelector('tbody').append(tr);}
 (x.requestMaterials||[]).forEach(row);if(!x.requestMaterials?.length)row();box.querySelector('#addRequestMaterial').onclick=()=>row();
 for(const id of ['prProgress','prMaterial']){const field=document.getElementById(id);field.setAttribute('lang','fr');field.setAttribute('spellcheck','true');field.insertAdjacentHTML('afterend',ui.assistant.toolsHtml(id,{translate:true,rewrite:true}));}
}
