import {mountInvoicedWork} from './invoiced-work.js';
import {activeRecord,projectsToInvoice,officeReports,invoiceProject} from './work-records.js';
import {openOfficeReports} from './office-reports.js';
import {durationHours} from './ops.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountOfficeWork(ui,root){
 if(!ui.c.isAdmin()){root.replaceChildren();return;}
 const projects=ui.c.getCatalog?.().projects||[],billProjects=projectsToInvoice(projects,ui.data.projectTracking),billInterventions=ui.data.interventions.filter(x=>!x.projectId&&x.status==='terminee'),reports=officeReports(ui.data);
 const notices=ui.data.interventions.filter(x=>activeRecord(x)&&(x.needsQuote||x.materialNeeded||x.requestMaterials?.length||(x.reportItems||[]).some(i=>i.needsQuote)));
 root.innerHTML=`<button type="button" class="officeReportTile" id="openOfficeReports"><span><strong>Comptes rendus</strong><small>Consulter les rapports · modifier · supprimer</small></span><span class="countBadge">${reports.length}</span><span aria-hidden="true">→</span></button><div class="adminGrid"><section class="panel"><h2>À facturer <span class="countBadge">${billProjects.length+billInterventions.length}</span></h2><h3>Chantiers terminés (${billProjects.length})</h3>${billProjects.map(p=>`<div class="row"><div><button type="button" class="documentLink" data-office-project="${esc(p.id)}">${esc(p.name)}</button><p>${p.category==='99'?'Archivé · ':''}Terminé · À facturer</p><button type="button" data-project-reports="${esc(p.id)}">Rapports du chantier</button></div><button type="button" data-project-invoice="${esc(p.id)}">Marquer facturé</button></div>`).join('')||'<p>Aucun chantier terminé à facturer.</p>'}<h3>Interventions achevées (${billInterventions.length})</h3>${billInterventions.map(x=>`<div class="row"><div><button type="button" class="documentLink" data-office-intervention="${esc(x.id)}">${esc(x.number)} · ${esc(x.clientName)}</button><p>${esc(x.workDone||x.title)} · ${esc(durationHours(x.actualStart||x.plannedStart,x.actualEnd||x.plannedEnd,x.pauseHours).toFixed(2))} h</p>${x.billingAgreement?`<p>${esc(x.billingAgreement)}</p>`:''}</div><button type="button" data-intervention-invoice="${esc(x.id)}">Marquer facturé</button></div>`).join('')||'<p>Aucune intervention achevée à facturer.</p>'}</section><section class="panel"><h2>Observations / matériel / devis complémentaires</h2>${notices.map(x=>`<div class="row"><div><button type="button" class="documentLink" data-office-intervention="${esc(x.id)}">${esc(x.projectName||x.clientName)} · ${esc(x.number)}</button><p>${esc(x.materialNeeded||x.progressNotes||'Compte rendu à examiner')}</p>${(x.reportItems||[]).filter(i=>i.needsQuote).map(i=>`<p><strong>${esc(i.title)}</strong> : ${esc(i.observation||i.action||'À examiner')}</p>`).join('')}${x.requestMaterials?.length?`<p>${x.requestMaterials.length} ligne(s) de matériel demandé</p>`:''}</div></div>`).join('')||'<p>Aucune demande signalée.</p>'}</section></div>`;
 const run=async action=>{try{await action();}catch(e){ui.c.toast('Action non terminée : '+e.message);}};
 root.querySelectorAll('[data-office-project]').forEach(b=>b.onclick=()=>run(async()=>{await ui.show('projects');await ui.c.openProject(b.dataset.officeProject);}));
 root.querySelectorAll('[data-office-intervention]').forEach(b=>b.onclick=()=>run(()=>ui.openIntervention(b.dataset.officeIntervention)));
 root.querySelectorAll('[data-project-reports]').forEach(b=>b.onclick=()=>run(async()=>{const p=projects.find(p=>p.id===b.dataset.projectReports);await ui.openProjectReports(p,await ui.c.projectMeta(p.id));}));
 root.querySelectorAll('[data-project-invoice]').forEach(b=>b.onclick=async()=>{if(b.disabled)return;const number=prompt('Numéro de facture (facultatif) :','');if(number===null)return;b.disabled=true;await run(async()=>{await invoiceProject(ui,projects.find(p=>p.id===b.dataset.projectInvoice),number);await ui.renderOffice();});b.disabled=false;});
 root.querySelectorAll('[data-intervention-invoice]').forEach(b=>b.onclick=async()=>{if(b.disabled)return;b.disabled=true;await run(()=>ui.markBilled(b.dataset.interventionInvoice));b.disabled=false;});
 mountInvoicedWork(ui,root);
 document.getElementById('openOfficeReports').onclick=()=>openOfficeReports(ui);
}
