import {activeRecord,isIndependentIntervention,completedRecord,projectsToInvoice,officeReports,invoiceProject} from './work-records.js';
import {REPORT_TYPES} from './project-report-details.js';
import {frDateTime,durationHours} from './ops.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const labels={project:'Chantier',intervention:'Intervention indépendante',visit:'Visite / devis'};
const reportState=r=>r.pdfSavedAt?'PDF enregistré':completedRecord(r)?'Compte rendu enregistré · PDF à vérifier':'Brouillon à reprendre';
export function mountOfficeWork(ui,root){
 if(!ui.c.isAdmin()){root.replaceChildren();return;}
 const projects=ui.c.getCatalog?.().projects||[],billProjects=projectsToInvoice(projects,ui.data.projectTracking),billInterventions=ui.data.interventions.filter(x=>isIndependentIntervention(x)&&x.status==='terminee'),reports=officeReports(ui.data);
 const notices=ui.data.interventions.filter(x=>activeRecord(x)&&(x.needsQuote||x.materialNeeded||x.requestMaterials?.length||(x.reportItems||[]).some(i=>i.needsQuote)));
 root.innerHTML=`<div class="adminGrid"><section class="panel"><h2>À facturer <span class="countBadge">${billProjects.length+billInterventions.length}</span></h2><h3>Chantiers terminés (${billProjects.length})</h3>${billProjects.map(p=>`<div class="row"><div><button type="button" class="documentLink" data-office-project="${esc(p.id)}">${esc(p.name)}</button><p>${p.category==='99'?'Archivé · ':''}Terminé · À facturer</p><button type="button" data-project-reports="${esc(p.id)}">Rapports du chantier</button></div><button type="button" data-project-invoice="${esc(p.id)}">Marquer facturé</button></div>`).join('')||'<p>Aucun chantier terminé à facturer.</p>'}<h3>Interventions achevées (${billInterventions.length})</h3>${billInterventions.map(x=>`<div class="row"><div><button type="button" class="documentLink" data-office-intervention="${esc(x.id)}">${esc(x.number)} · ${esc(x.clientName)}</button><p>${esc(x.workDone||x.title)} · ${esc(durationHours(x.actualStart||x.plannedStart,x.actualEnd||x.plannedEnd,x.pauseHours).toFixed(2))} h</p>${x.billingAgreement?`<p>${esc(x.billingAgreement)}</p>`:''}</div><button type="button" data-intervention-invoice="${esc(x.id)}">Marquer facturé</button></div>`).join('')||'<p>Aucune intervention achevée à facturer.</p>'}</section><section class="panel"><h2>Observations / matériel / devis complémentaires</h2>${notices.map(x=>`<div class="row"><div><button type="button" class="documentLink" data-office-intervention="${esc(x.id)}">${esc(x.projectName||x.clientName)} · ${esc(x.number)}</button><p>${esc(x.materialNeeded||x.progressNotes||'Compte rendu à examiner')}</p>${(x.reportItems||[]).filter(i=>i.needsQuote).map(i=>`<p><strong>${esc(i.title)}</strong> : ${esc(i.observation||i.action||'À examiner')}</p>`).join('')}${x.requestMaterials?.length?`<p>${x.requestMaterials.length} ligne(s) de matériel demandé</p>`:''}</div></div>`).join('')||'<p>Aucune demande signalée.</p>'}</section></div><section class="panel officeReports"><h2>Tous les rapports <span class="countBadge">${reports.length}</span></h2><div class="formGrid"><label>Rechercher<input type="search" id="officeReportSearch" placeholder="Affaire, client, numéro du rapport…"></label><label>Type<select id="officeReportType"><option value="">Tous</option><option value="project">Chantiers</option><option value="intervention">Interventions indépendantes</option><option value="visit">Visites / devis</option></select></label><label>État<select id="officeReportState"><option value="">Tous</option><option value="saved">Enregistrés</option><option value="draft">Brouillons à reprendre</option></select></label></div><p id="officeReportCount" role="status"></p><div id="officeReportList"></div></section>`;
 const run=async action=>{try{await action();}catch(e){ui.c.toast('Action non terminée : '+e.message);}};
 root.querySelectorAll('[data-office-project]').forEach(b=>b.onclick=()=>run(async()=>{await ui.show('projects');await ui.c.openProject(b.dataset.officeProject);}));
 root.querySelectorAll('[data-office-intervention]').forEach(b=>b.onclick=()=>run(()=>ui.openIntervention(b.dataset.officeIntervention)));
 root.querySelectorAll('[data-project-reports]').forEach(b=>b.onclick=()=>run(async()=>{const p=projects.find(p=>p.id===b.dataset.projectReports);await ui.openProjectReports(p,await ui.c.projectMeta(p.id));}));
 root.querySelectorAll('[data-project-invoice]').forEach(b=>b.onclick=async()=>{if(b.disabled)return;const number=prompt('Numéro de facture (facultatif) :','');if(number===null)return;b.disabled=true;await run(async()=>{await invoiceProject(ui,projects.find(p=>p.id===b.dataset.projectInvoice),number);await ui.renderOffice();});b.disabled=false;});
 root.querySelectorAll('[data-intervention-invoice]').forEach(b=>b.onclick=async()=>{if(b.disabled)return;b.disabled=true;await run(()=>ui.markBilled(b.dataset.interventionInvoice));b.disabled=false;});
 const draw=()=>{
  const q=norm(root.querySelector('#officeReportSearch').value),kind=root.querySelector('#officeReportType').value,state=root.querySelector('#officeReportState').value;
  const rows=reports.filter(({kind:k,record:r})=>(!kind||kind===k)&&(!state||(!!r.pdfSavedAt||completedRecord(r))===(state==='saved'))&&norm([r.projectName,r.number,r.devis,r.clientName,r.title,r.siteAddress].join(' ')).includes(q));
  root.querySelector('#officeReportCount').textContent=rows.length+' rapport(s)';
  const list=root.querySelector('#officeReportList');list.innerHTML=rows.map(({kind,record:r},i)=>`<article class="row"><div><button type="button" class="documentLink" data-open-report="${i}">${esc(r.projectName||r.clientName||r.title||'Compte rendu')} · ${esc(r.number)}</button><p>${labels[kind]}${kind==='project'?' · '+esc(REPORT_TYPES[r.reportKind]||'Compte rendu'):''} · ${reportState(r)}</p><p>${esc(frDateTime(r.actualStart||r.plannedStart||r.createdAt))}</p></div>${r.pdfFileId?`<button type="button" data-open-report-pdf="${i}">Voir le PDF</button>`:''}</article>`).join('')||'<p>Aucun rapport correspondant.</p>';
  list.querySelectorAll('[data-open-report]').forEach(b=>b.onclick=()=>run(()=>{const r=rows[+b.dataset.openReport];return r.kind==='visit'?ui.openVisit(r.record.id):ui.openIntervention(r.record.id);}));
  list.querySelectorAll('[data-open-report-pdf]').forEach(b=>b.onclick=()=>run(()=>{const r=rows[+b.dataset.openReportPdf].record;return ui.c.openAlertDocument({id:r.pdfFileId,name:r.pdfName||r.number+'.pdf'});}));
 };
 root.querySelector('#officeReportSearch').oninput=draw;root.querySelector('#officeReportType').onchange=draw;root.querySelector('#officeReportState').onchange=draw;draw();
}
