const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function eventProjectIds(e){return e.kind==='project'?[...new Set([e.linkId,...(e.additionalProjectIds||[])].filter(Boolean))]:[];}
export function projectEventLabel(e,projects){return eventProjectIds(e).map(id=>projects.find(p=>p.id===id)?.name||id).join(' + ')||e.title||'';}
export function mountPlanningAffairs(ui,e){
 const box=document.createElement('section');box.id='planningAffairs';box.className='panel';
 box.innerHTML=`<h3>Plusieurs affaires dans ce rendez-vous</h3><p>Une seule équipe et un seul bloc au calendrier. Cochez les autres affaires réalisées pendant cette journée.</p><label>Nom court du rendez-vous<input id="eventGroupTitle" placeholder="Ex. UCPA · Patinoire" value="${esc(e.groupTitle||'')}"></label><details><summary>Ajouter / retirer des affaires</summary>${ui.c.getCatalog().projects.map(p=>`<label class="inline"><input type="checkbox" data-linked-affair value="${esc(p.id)}" ${(e.additionalProjectIds||[]).includes(p.id)?'checked':''}> ${esc(p.name)}</label>`).join('')}</details><label>Organisation de la journée<textarea id="eventInstructions" placeholder="Ex. affaire 1194 le matin, affaire 715 l’après-midi">${esc(e.instructions||'')}</textarea></label><p class="muted">Les heures de l’équipe sont comptées une fois. Pour répartir précisément les heures entre affaires, utilisez des créneaux séparés ou les rapports propres à chaque affaire.</p>`;
 document.getElementById('eventForm').querySelector('.teamAssignBox').before(box);
 const sync=()=>{const [kind,id]=document.getElementById('eventLink').value.split('|');box.hidden=kind!=='project';box.querySelectorAll('[data-linked-affair]').forEach(cb=>{cb.disabled=cb.value===id;});};
 document.getElementById('eventLink').addEventListener('change',sync);sync();
}
export function readPlanningAffairs(kind,linkId){return kind==='project'?{additionalProjectIds:[...document.querySelectorAll('[data-linked-affair]:checked')].map(cb=>cb.value).filter(id=>id!==linkId),groupTitle:document.getElementById('eventGroupTitle').value.trim(),instructions:document.getElementById('eventInstructions').value.trim()}:{additionalProjectIds:[],groupTitle:'',instructions:''};}
