import {makeId,nextVisitNumber} from './ops.js?v=3.4.2';
import {mountVisitFiles} from './visit-followup.js';
import {isIndependentIntervention} from './work-records.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const isReception=v=>v.type==='Réception de chantier / intervention';
export async function completeReception(ui,v,notes){
 const before=structuredClone(v);
 Object.assign(v,{notes,status:'terminee',completedAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
 try{await ui.save('visits');}catch(e){Object.keys(v).forEach(k=>delete v[k]);Object.assign(v,before);throw e;}
}
export function mountReception(ui,root){
 if(!ui.canPlan())return;
 const b=document.createElement('button');b.textContent='+ Réception';b.type='button';root.querySelector('.pageHeading').append(b);b.onclick=()=>editReception(ui);
}
export function editReception(ui,existing=null){
 if(!ui.canPlan())return;
 const v=existing||{id:makeId('vis'),number:nextVisitNumber(ui.data.visits),type:'Réception de chantier / intervention',teamIds:[],status:'a_planifier'};
 const sources=[...ui.c.getCatalog().projects.map(p=>({kind:'project',id:p.id,label:p.name})),...ui.data.interventions.filter(isIndependentIntervention).map(i=>({kind:'intervention',id:i.id,label:i.number+' · '+i.clientName}))];
 ui.c.modal('Réception de chantier / intervention',`<form id="receptionForm"><p>Rendez-vous lié au dossier existant. Aucun rapport obligatoire.</p><label>Dossier concerné<select id="rSource" required><option value="">Choisir…</option>${sources.map(s=>`<option value="${esc(s.kind+'|'+s.id)}">${s.kind==='project'?'Chantier':'Intervention'} · ${esc(s.label)}</option>`).join('')}</select></label><div class="formGrid">${[['Address','Adresse',v.siteAddress],['Contact','Contact sur place',v.siteContact],['Phone','Téléphone',v.sitePhone],['Email','E-mail',v.siteEmail],['Access','Accès / consignes',v.siteAccess],['Request','Objet du rendez-vous',v.request]].map(([id,label,value])=>`<div class="wide"><label>${label}<input id="r${id}" value="${esc(value||'')}" ${id==='Address'?'required':''}></label></div>`).join('')}<div><label>Début<input id="rStart" type="datetime-local" required value="${ui.localDT(v.plannedStart)}"></label></div><div><label>Fin<input id="rEnd" type="datetime-local" required value="${ui.localDT(v.plannedEnd)}"></label></div></div><fieldset><legend>Participants OPUS</legend>${ui.data.people.filter(p=>p.active!==false).map(p=>`<label style="display:block"><input type="checkbox" name="rTeam" value="${esc(p.id)}" ${(v.teamIds||[]).includes(p.id)?'checked':''}> ${esc(p.name||[p.lastName,p.firstName].filter(Boolean).join(' '))}</label>`).join('')}</fieldset><label>Autres participants<input id="rGuests" value="${esc(v.receptionGuests||'')}" placeholder="Client, syndic, bureau de contrôle…"></label><p id="rError" role="status"></p><button id="rSave">Enregistrer le rendez-vous</button></form>`);
 const form=document.getElementById('receptionForm'),select=document.getElementById('rSource'),button=document.getElementById('rSave'),error=document.getElementById('rError');let sourceName=v.clientName||'',loading=false;
 select.value=v.receptionKind? v.receptionKind+'|'+v.receptionId:'';
 select.onchange=async()=>{const value=select.value,s=sources.find(s=>s.kind+'|'+s.id===value);if(!s)return;loading=true;button.disabled=true;error.textContent='Chargement du dossier…';try{const m=s.kind==='project'?await ui.c.projectMeta(s.id):ui.data.interventions.find(i=>i.id===s.id);if(select.value!==value)return;sourceName=m.clientName||m.client||s.label;const fields={Address:m.adresse||m.siteAddress,Contact:m.contact||m.siteContact,Phone:m.telephone||m.sitePhone||m.phone,Email:m.email||m.siteEmail,Access:m.notes||m.siteAccess,Request:'Réception · '+s.label};for(const [key,val]of Object.entries(fields))document.getElementById('r'+key).value=val||'';error.textContent='';}catch(e){error.textContent='Dossier non chargé : '+e.message;return;}finally{loading=false;button.disabled=!!error.textContent;}};
 form.onsubmit=async ev=>{ev.preventDefault();if(loading)return;button.disabled=true;try{const s=sources.find(s=>s.kind+'|'+s.id===select.value);if(!s)throw Error('Choisissez le dossier concerné.');const start=ui.toISO(document.getElementById('rStart').value),end=ui.toISO(document.getElementById('rEnd').value);if(!(new Date(end)>new Date(start)))throw Error('La fin doit être après le début.');const draft={...v,receptionKind:s.kind,receptionId:s.id,receptionLabel:s.label,clientName:sourceName,title:'Réception · '+s.label,plannedStart:start,plannedEnd:end,teamIds:[...form.querySelectorAll('[name=rTeam]:checked')].map(e=>e.value),receptionGuests:document.getElementById('rGuests').value,updatedAt:new Date().toISOString(),status:v.status==='terminee'?'terminee':'planifiee'};for(const [key,field]of Object.entries({Address:'siteAddress',Contact:'siteContact',Phone:'sitePhone',Email:'siteEmail',Access:'siteAccess',Request:'request'}))draft[field]=document.getElementById('r'+key).value.trim();const before=ui.data.visits;ui.data.visits=existing?before.map(x=>x.id===v.id?draft:x):[...before,draft];try{await ui.save('visits');}catch(e){ui.data.visits=before;throw e;}existing=draft;Object.assign(v,draft);await ui.upsertLinkedEvent('visit',draft);document.getElementById('modal').close();await ui.renderVisits();ui.c.toast('Réception enregistrée dans le calendrier.');}catch(e){error.textContent='Enregistrement à vérifier : '+e.message;button.disabled=false;}};
}
export function openReception(ui,v){
 ui.c.modal('Réception · '+(v.receptionLabel||v.number),`<p>${esc(v.siteAddress)}</p><p>${esc(v.siteContact)} · ${esc(v.sitePhone)}</p><p style="white-space:pre-wrap">${esc(v.siteAccess)}</p><p>${esc(v.request)}</p><p>Participants : ${esc(ui.teamNames(v.teamIds))} ${esc(v.receptionGuests)}</p><p>${v.plannedStart?esc(new Date(v.plannedStart).toLocaleString('fr-FR')):''}</p><label>Réserves / observations (facultatif)<textarea id="rNotes">${esc(v.notes||'')}</textarea></label><div id="rActions"><p role="status">${v.status==='terminee'?'Réception effectuée':''}</p>${ui.canPlan()?'<button id="rDone" style="background:#ddf3e3;color:#175c38">Réception effectuée — enregistrer</button><button id="rEdit">Modifier le rendez-vous</button>':''}</div>`);
 mountVisitFiles(ui,v,document.getElementById('rActions'));
 if(ui.canPlan()){document.getElementById('rEdit').onclick=()=>editReception(ui,v);document.getElementById('rDone').onclick=async ev=>{const b=ev.currentTarget;b.disabled=true;try{await completeReception(ui,v,document.getElementById('rNotes').value);ui.visitView='finished';await ui.renderVisits();ui.c.toast('Réception effectuée et enregistrée.');document.getElementById('modal').close();}catch(e){document.querySelector('#rActions [role=status]').textContent=e.message;b.disabled=false;}};}
}
