import {makeId} from './ops.js?v=3.4.2';
import {ABSENCE_TYPES,validatePeriods,absenceLabel,closureAt,absenceAt,payrollCsv} from './workforce.js?v=20260914';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function absenceBadges(ui,date){return ui.data.people.filter(p=>p.active!==false).flatMap(p=>absenceAt(p,date).map(a=>`<div class="opusAbsent">${esc(p.name)} · ${ui.role()==='admin'?esc(absenceLabel(a)):'Indisponible'}</div>`)).join('');}
export function manageClosures(ui){
 if(ui.role()!=='admin')return;
 const periods=structuredClone(ui.data.closures||[]);
 ui.c.modal('Fermetures de l’entreprise',`<form id="closuresForm"><p>Noël, vacances d’été… Les dates sont incluses. Les jours fermés apparaissent en rouge. Les rendez-vous existants sont conservés et signalés pour replanification.</p><div id="closureRows"></div><button type="button" id="addClosure" class="secondary">+ Ajouter une fermeture</button><p id="closureError" role="alert"></p><button type="submit">Enregistrer les fermetures</button></form>`);
 const draw=()=>{document.getElementById('closureRows').innerHTML=periods.map((p,i)=>`<fieldset><legend>Fermeture ${i+1}</legend><label>Libellé<input data-row="${i}" data-key="label" value="${esc(p.label)}" required></label><div class="grid2"><label>Du<input type="date" data-row="${i}" data-key="start" value="${esc(p.start)}" required></label><label>Au inclus<input type="date" data-row="${i}" data-key="end" value="${esc(p.end)}" required></label></div><button type="button" class="danger" data-remove="${i}">Supprimer cette période</button></fieldset>`).join('');document.querySelectorAll('[data-row]').forEach(el=>el.oninput=()=>periods[+el.dataset.row][el.dataset.key]=el.value);document.querySelectorAll('[data-remove]').forEach(el=>el.onclick=()=>{periods.splice(+el.dataset.remove,1);draw();});};draw();
 document.getElementById('addClosure').onclick=()=>{periods.push({id:makeId('closure'),label:'',start:'',end:''});draw();};
 document.getElementById('closuresForm').onsubmit=async ev=>{ev.preventDefault();const b=ev.target.querySelector('[type=submit]');b.disabled=true;try{validatePeriods(periods);await ui.repo.save('closures',periods);ui.data.closures=periods;document.getElementById('modal').close();await ui.renderCalendar();ui.c.toast('Fermetures enregistrées.');}catch(e){document.getElementById('closureError').textContent=e.message;}finally{b.disabled=false;}};
}
export function editResource(ui,existing,forceExternal=false){
 if(!ui.canPlan()||ui.role()==='manager'&&existing?.type!=='external'&&existing)return;
 const p=structuredClone(existing||{id:makeId('pers'),name:'',email:'',type:forceExternal?'external':'internal',role:forceExternal?'prestataire':'technicien',weeklyTarget:forceExternal?0:39,vehicle:false,active:true,schoolPeriods:[],absences:[]});p.absences||=[];p.schoolPeriods||=[];
 ui.c.modal('Équipe · '+(existing?p.name:'Nouvelle ressource'),`<form id="resourceForm"><div class="formGrid"><label>Nom<input id="wrName" value="${esc(p.name)}" required></label><label>E-mail professionnel<input id="wrEmail" type="email" value="${esc(p.email)}"></label><label>Matricule<input id="wrCode" value="${esc(p.employeeCode)}"></label><label>Fonction<select id="wrRole"><option value="technicien">Technicien</option><option value="apprenti">Apprenti</option><option value="prestataire">Prestataire</option></select></label><label>Base hebdomadaire (h)<input id="wrHours" type="number" min="0" step="0.5" value="${p.weeklyTarget}"></label><label><input id="wrVehicle" type="checkbox" ${p.vehicle?'checked':''}> Véhicule</label><label><input id="wrActive" type="checkbox" ${p.active!==false?'checked':''}> Actif</label>${p.type==='external'?`<label>Début de mission<input id="wrFrom" type="date" value="${esc(p.availableFrom)}"></label><label>Fin de mission<input id="wrTo" type="date" value="${esc(p.availableTo)}"></label>`:''}</div><h3>Absences / congés</h3><p>Périodes en journées entières, dates incluses. Les horaires concernés sont indicatifs pour la paie. Ne saisissez pas de diagnostic médical.</p><div id="wrAbsences"></div><button type="button" id="wrAddAbsence" class="secondary">+ Absence / congé / maladie</button><h3>École</h3><div id="wrSchool"></div><button type="button" id="wrAddSchool" class="secondary">+ Période école</button><p id="wrError" role="alert"></p><button type="submit">Enregistrer</button></form>`);
 document.getElementById('wrRole').value=p.role;
 const draw=()=>{for(const [key,id] of [['absences','wrAbsences'],['schoolPeriods','wrSchool']]){document.getElementById(id).innerHTML=p[key].map((a,i)=>`<fieldset>${key==='absences'?`<label>Motif<select data-list="${key}" data-index="${i}" data-field="type">${!a.type?`<option value="">${esc(a.label||'Choisir le motif')}</option>`:''}${Object.entries(ABSENCE_TYPES).map(([v,label])=>`<option value="${v}" ${a.type===v?'selected':''}>${label}</option>`).join('')}</select></label>`:''}<div class="grid2"><label>Du<input type="date" data-list="${key}" data-index="${i}" data-field="start" value="${esc(a.start)}" required></label><label>Au inclus<input type="date" data-list="${key}" data-index="${i}" data-field="end" value="${esc(a.end)}" required></label></div><button type="button" class="danger" data-list="${key}" data-delete="${i}">Supprimer la période</button></fieldset>`).join('');}document.querySelectorAll('[data-field]').forEach(el=>el.onchange=()=>{const a=p[el.dataset.list][+el.dataset.index];a[el.dataset.field]=el.value;if(el.dataset.field==='type')a.label=ABSENCE_TYPES[el.value]||a.label;});document.querySelectorAll('[data-delete]').forEach(el=>el.onclick=()=>{p[el.dataset.list].splice(+el.dataset.delete,1);draw();});};draw();
 document.getElementById('wrAddAbsence').onclick=()=>{p.absences.push({id:makeId('abs'),type:'conge',label:'Congés payés',start:'',end:''});draw();};document.getElementById('wrAddSchool').onclick=()=>{p.schoolPeriods.push({start:'',end:'',label:'École'});draw();};
 document.getElementById('resourceForm').onsubmit=async ev=>{ev.preventDefault();const b=ev.target.querySelector('[type=submit]');b.disabled=true;try{validatePeriods([...p.absences,...p.schoolPeriods]);p.name=document.getElementById('wrName').value.trim();p.email=document.getElementById('wrEmail').value.trim();p.employeeCode=document.getElementById('wrCode').value.trim();p.role=p.type==='external'?'prestataire':document.getElementById('wrRole').value;p.weeklyTarget=Number(document.getElementById('wrHours').value);p.vehicle=document.getElementById('wrVehicle').checked;p.active=document.getElementById('wrActive').checked;if(p.type==='external'){p.availableFrom=document.getElementById('wrFrom').value;p.availableTo=document.getElementById('wrTo').value;if(p.availableFrom&&p.availableTo)validatePeriods([{start:p.availableFrom,end:p.availableTo}]);}p.officeManaged=true;p.updatedAt=new Date().toISOString();const next=ui.data.people.map(x=>x.id===p.id?p:x);if(!existing)next.push(p);await ui.repo.save('people',next);ui.data.people=next;ui.c.toast('Ressource enregistrée. Vérifiez les rendez-vous déjà affectés pendant ses absences.');ui.peopleManager();}catch(e){document.getElementById('wrError').textContent=e.message;}finally{b.disabled=false;}};
}
export function exportPayroll(ui,month){if(ui.role()!=='admin')return;try{ui.c.download(new Blob([payrollCsv(ui.data,month)],{type:'text/csv;charset=utf-8'}),`OPUS_RECAP_PAIE_${month}.csv`);ui.c.toast('Récapitulatif exporté : vérifiez les lignes à compléter avant transmission à la paie.');}catch(e){ui.c.toast(e.message);}}
