import {Graph,safeName} from '../lib/cloud.js';
import {makePDF} from './pdf.js';
const $=id=>document.getElementById(id),fields=['supplier','number','date','clientReference','deliveryMode','destination','availability','notes'];
let config,msal,g,projects=[],images=[],warnings=[],allowed=false,busy=false;
const status=t=>$('status').textContent=t;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){status(e.message||'Action impossible.');}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
async function token(){return (await msal.acquireTokenSilent({scopes:config.scopes,account:msal.getActiveAccount()})).accessToken;}
async function api(method,body){const r=await fetch('/api/commande',{method,headers:{Authorization:'Bearer '+await token(),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(65000)});const d=await r.json().catch(()=>({error:'Réponse serveur illisible.'}));if(!r.ok)throw Error(d.error);return d;}
$('login').onclick=()=>run(async()=>{sessionStorage.setItem('opus-auth-return','/commandes/');await msal.loginRedirect({scopes:config.scopes,prompt:'select_account'});});
async function init(){config=await(await fetch('../config.json',{cache:'no-store'})).json();const M=await import('../vendor/msal.js');msal=new M.PublicClientApplication({auth:{clientId:config.clientId,authority:`https://login.microsoftonline.com/${config.tenant}`,redirectUri:new URL('../auth.html',location.href).href},cache:{cacheLocation:'sessionStorage'}});await msal.initialize();const account=msal.getActiveAccount()||msal.getAllAccounts()[0];if(!account){status('Connectez-vous pour préparer vos commandes.');return;}msal.setActiveAccount(account);await api('GET');allowed=true;$('locked').hidden=true;$('workspace').hidden=false;$('login').textContent='Changer de compte';status('Votre espace personnel est ouvert.');g=new Graph(token);try{await g.connect(config);projects=(await g.projects()).projects;$('project').innerHTML='<option value="">Choisir un chantier</option>'+projects.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');}catch(e){status('PDF disponible. Liste des chantiers inaccessible : '+e.message);}addRow();}
function addRow(v={}){const tr=document.createElement('tr');tr.innerHTML=['reference','description','quantity','unit'].map(k=>`<td><input aria-label="${k}" data-field="${k}" value="${esc(v[k]||'')}"></td>`).join('')+'<td><button title="Supprimer cette ligne">×</button></td>';tr.querySelector('button').onclick=()=>{tr.remove();$('approved').checked=false;};$('items').append(tr);}
function read(){return Object.fromEntries([...fields.map(k=>[k,$(k).value.trim()]),['warnings',warnings],['items',[...$('items').rows].map(tr=>Object.fromEntries([...tr.querySelectorAll('input')].map(i=>[i.dataset.field,i.value.trim()])))]]);}
function fill(o){for(const k of fields)$(k).value=String(o[k]||'');$('items').replaceChildren();for(const v of o.items||[])addRow(v);warnings=Array.isArray(o.warnings)?o.warnings.map(String):[];$('warnings').textContent=warnings.join('\n');$('warnings').hidden=!warnings.length;$('approved').checked=false;if(/buc/i.test(o.destination||''))$('group').value='depot';}
function validated(){if(!allowed)throw Error('Connectez-vous à votre compte.');const o=read();if(!o.supplier||!o.number||!o.destination||!['retrait','livraison'].includes(o.deliveryMode))throw Error('Renseignez le fournisseur, le numéro de commande, le mode et le lieu.');if(!o.items.length||o.items.some(i=>!i.description||!/^\d+(?:[.,]\d+)?$/.test(i.quantity)||Number(i.quantity.replace(',','.'))<=0))throw Error('Chaque ligne doit avoir une désignation et une quantité positive vérifiée.');if(!$('approved').checked)throw Error('Cochez la validation après avoir relu le bon.');return o;}
$('workspace').addEventListener('input',e=>{if(e.target.id!=='approved')$('approved').checked=false;});
$('add').onclick=()=>{addRow();$('approved').checked=false;};
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);}
const logoKey=()=> 'opus-order-logo:'+String(msal?.getActiveAccount()?.homeAccountId||'')+':'+$('supplier').value.trim().toLowerCase();
async function imageData(file,max=2000){const bitmap=await createImageBitmap(file);const scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)),c=document.createElement('canvas');c.width=Math.round(bitmap.width*scale);c.height=Math.round(bitmap.height*scale);const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(bitmap,0,0,c.width,c.height);bitmap.close();return c.toDataURL('image/jpeg',.88);}
function sources(){ $('sources').innerHTML=images.map((x,i)=>`<div class="source"><img src="${x.data}" alt="Page importée"><span>${esc(x.name)}</span><button data-remove="${i}">×</button></div>`).join('');$('sources').querySelectorAll('button').forEach(b=>b.onclick=()=>{images.splice(Number(b.dataset.remove),1);sources();});}
$('files').onchange=()=>run(async()=>{const staged=[];for(const file of $('files').files){if(file.size>20000000)throw Error('Fichier limité à 20 Mo.');if(file.type==='application/pdf'){const pdfjs=await import('../vendor/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc=new URL('../vendor/pdf.worker.mjs',import.meta.url).href;const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;try{if(pdf.numPages+images.length+staged.length>8)throw Error('Maximum 8 pages par commande.');for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n),base=page.getViewport({scale:1}),view=page.getViewport({scale:Math.min(2,2000/Math.max(base.width,base.height))}),c=document.createElement('canvas');c.width=view.width;c.height=view.height;await page.render({canvasContext:c.getContext('2d'),viewport:view}).promise;staged.push({name:file.name+' · page '+n,data:c.toDataURL('image/jpeg',.88)});}}finally{await pdf.destroy();}}else if(['image/png','image/jpeg','image/webp'].includes(file.type)){staged.push({name:file.name,data:await imageData(file)});}else throw Error('Utilisez une image ou un PDF.');}if(images.length+staged.length>8)throw Error('Maximum 8 pages.');if([...images,...staged].reduce((n,x)=>n+x.data.length,0)>3300000)throw Error('Images trop volumineuses. Importez moins de pages.');images.push(...staged);sources();status('Sources ajoutées. Cliquez sur Lire la commande.');$('files').value='';});
$('extract').onclick=()=>run(async()=>{if(!allowed)throw Error('Connectez-vous.');if($('items').querySelector('input')?.value||$('number').value){if(!confirm('Remplacer la fiche actuelle par une nouvelle lecture ?'))return;}status('Lecture de la commande…');const {order}=await api('POST',{text:$('sourceText').value,images:images.map(x=>x.data)});fill(order);status('Lecture terminée : vérifiez toutes les lignes et le lieu avant validation.');});
$('buc').onclick=()=>{$('destination').value='OPUS ELEC — Dépôt de Buc\n100 rue des Artisans\n78530 BUC';$('deliveryMode').value='livraison';$('group').value='depot';$('approved').checked=false;};
$('supplierLogo').onchange=()=>run(async()=>{if(!$('supplier').value.trim())throw Error('Renseignez d’abord le fournisseur.');const f=$('supplierLogo').files[0];if(!f)return;if(f.size>5000000)throw Error('Logo limité à 5 Mo.');localStorage.setItem(logoKey(),await imageData(f,600));$('approved').checked=false;status('Logo enregistré pour ce fournisseur sur cet ordinateur.');});
$('removeLogo').onclick=()=>{localStorage.removeItem(logoKey());$('approved').checked=false;status('Logo retiré.');};
async function pdf(o){return makePDF(o,{logo:await imageURL('../assets/logo.png'),supplierLogo:localStorage.getItem(logoKey())||'',project:projects.find(p=>p.id===$('project').value)?.name||''});}
async function imageURL(url){return new Promise(async(resolve,reject)=>{try{const r=await fetch(url);if(!r.ok)throw Error('Logo OPUS indisponible.');const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(await r.blob());}catch(e){reject(e);}});}
$('pdf').onclick=()=>run(async()=>{const o=validated();download(await pdf(o),safeName('BC_'+o.supplier+'_'+o.number)+'.pdf');status('PDF téléchargé.');});
$('archive').onclick=()=>run(async()=>{const o=validated(),p=projects.find(p=>p.id===$('project').value);if(!p)throw Error('Choisissez le chantier de destination.');const group=$('group').value==='depot'?'DEPOT_BUC':'FOURNISSEURS';if(!confirm(`Enregistrer ce bon dans ${p.name} / ${group} ?`))return;await api('GET');status('Enregistrement dans OPUS…');const blob=await pdf(o),root=await g.folder(p.id,'03_COMMANDES');let dest=await g.folder(root.id,group);if(group==='FOURNISSEURS')dest=await g.folder(dest.id,safeName(o.supplier));const item=await g.upload(dest.id,safeName('BC_'+o.supplier+'_'+o.number)+'.pdf',blob);status('PDF enregistré dans '+p.name+' / '+group+' : '+item.name);});
$('draft').onclick=()=>{download(new Blob([JSON.stringify({version:1,order:read()},null,2)],{type:'application/json'}),'OPUS_brouillon_commande.json');status('Brouillon téléchargé. Les images sources ne sont pas incluses.');};
$('loadDraft').onchange=()=>run(async()=>{const f=$('loadDraft').files[0];if(!f)return;if(f.size>1000000)throw Error('Brouillon trop volumineux.');const d=JSON.parse(await f.text());if(d.version!==1||!Array.isArray(d.order?.items)||d.order.items.length>300)throw Error('Brouillon invalide.');if(!confirm('Remplacer le bon actuel par ce brouillon ?'))return;fill(d.order);status('Brouillon ouvert, à vérifier avant export.');});
$('new').onclick=()=>{if(!confirm('Effacer le bon et ses sources pour préparer une nouvelle commande ?'))return;fill({});addRow();images=[];sources();$('sourceText').value='';$('project').value='';$('group').value='supplier';};
let install;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();install=e;$('install').hidden=false;});$('install').onclick=async()=>{await install?.prompt();$('install').hidden=true;};
window.addEventListener('beforeunload',e=>{if(allowed&&($('number').value||images.length||$('sourceText').value)){e.preventDefault();e.returnValue='';}});
init().catch(e=>status(e.message));

if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{});
