import {safeName} from '../lib/cloud.js';
import {makePDF} from './pdf.js';
import {installPdfFonts} from '../lib/pdf-fonts.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function newDepotRecord(){const id=crypto.randomUUID();return {id,number:'DEP-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+id.slice(0,6).toUpperCase(),date:new Date().toISOString().slice(0,10),projectId:'',projectName:'',state:'À préparer',recipient:'',collectedAt:'',boxes:1,notes:'',items:[]};}
export function validateDepot(d){if(!d.projectId)throw Error('Choisissez le chantier.');if(!Number.isInteger(d.boxes)||d.boxes<1||d.boxes>30)throw Error('Indiquez de 1 à 30 cartons.');if(!['À préparer','Prêt','Récupéré'].includes(d.state))throw Error('État invalide.');if(d.state==='Récupéré'&&(!d.recipient.trim()||!d.collectedAt))throw Error('Renseignez la personne et la date de récupération.');if(!d.items.length||d.items.some(x=>!x.description.trim()||!/^\d+(?:[.,]\d+)?$/.test(x.quantity)||Number(x.quantity.replace(',','.'))<=0))throw Error('Chaque matériel doit avoir une désignation et une quantité positive.');}
export function depotOrder(d){return {supplier:'OPUS ELEC — Dépôt de Buc',number:d.number,date:d.date,clientReference:d.projectName,deliveryMode:'retrait',destination:'Dépôt OPUS ELEC — Buc',availability:d.state,notes:[d.notes,d.recipient?'Récupéré par : '+d.recipient:'',d.collectedAt?'Date de récupération : '+d.collectedAt:'',d.boxes+' carton(s)'].filter(Boolean).join('\n'),items:d.items,internal:true};}
export async function labelPDF(d){validateDepot(d);const {jsPDF}=await import('../vendor/jspdf.js');const p=new jsPDF({orientation:'landscape',unit:'mm',format:'a6'});await installPdfFonts(p);const r=await fetch(new URL('../assets/logo.png',import.meta.url));if(!r.ok)throw Error('Logo indisponible.');const logo=new Uint8Array(await r.arrayBuffer());for(let i=1;i<=d.boxes;i++){if(i>1)p.addPage();p.addImage(logo,'PNG',8,7,37,12);p.setTextColor(12,61,99);p.setFont('OpusSans','bold');p.setFontSize(13);p.text('MATÉRIEL DÉPÔT',140,15,{align:'right'});p.setFontSize(17);let title=p.splitTextToSize(d.projectName,132);if(title.length>3){p.setFontSize(12);title=p.splitTextToSize(d.projectName,132);}p.text(title.slice(0,3),8,32);p.setFontSize(12);p.text('CARTON '+i+' / '+d.boxes+' — '+d.state,8,62);p.setFont('OpusSans','normal');p.setFontSize(9);p.text('Bon interne : '+d.number,8,72);p.text('Dépôt de Buc · Préparé le '+d.date,8,80);p.text('Contenu détaillé : consulter le bon du chantier.',8,88);p.setDrawColor(160);p.rect(4,4,140,97);}return p.output('blob');}
export function mountDepot(ctx){
 const root=document.getElementById('depotPage');let record=newDepotRecord(),baseVersion=null,history=[];const $=id=>root.querySelector('#'+id);
 async function folder(){const sys=await ctx.g().folder('root','_OPUS_SYSTEM');return ctx.g().folder(sys.id,'DEPOT_BONS');}
 async function records(){const f=await folder(),files=(await ctx.g().children(f.id)).filter(x=>x.file&&x.name.endsWith('.json'));const all=[];for(const x of files)all.push(await ctx.g().json(x.id));const latest=new Map();for(const d of all){const old=latest.get(d.id);if(!old||d.updatedAt>old.updatedAt)latest.set(d.id,d);}return [...latest.values()].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));}
 function draw(){root.innerHTML=`<div class="card"><h2>Matériel à récupérer au dépôt de Buc</h2><p>Préparez la liste affectée au chantier, puis imprimez le bon interne et les étiquettes. Le suivi porte sur ces préparations, sans calcul automatique du stock restant.</p><button id="dn" class="secondary">Nouveau bon interne</button> <button id="dh" class="secondary">Actualiser le suivi enregistré</button><div id="depotHistory"></div><div class="grid"><label>N° bon<input id="dnumber" readonly value="${esc(record.number)}"></label><label>Date de préparation<input id="ddate" type="date" value="${esc(record.date)}"></label><label>Chantier<select id="dproject"><option value="">Choisir</option>${ctx.projects().map(p=>`<option value="${esc(p.id)}" ${p.id===record.projectId?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><label>État<select id="dstate">${['À préparer','Prêt','Récupéré'].map(s=>`<option ${s===record.state?'selected':''}>${s}</option>`).join('')}</select></label><label>Récupéré par<input id="drecipient" value="${esc(record.recipient)}"></label><label>Date de récupération<input id="dcollected" type="date" value="${esc(record.collectedAt)}"></label><label>Nombre de cartons<input id="dboxes" type="number" min="1" max="30" value="${record.boxes}"></label></div><label>Consignes<textarea id="dnotes">${esc(record.notes)}</textarea></label><div class="tablewrap"><table><thead><tr><th>Référence</th><th>Matériel</th><th>Quantité</th><th>Unité</th><th></th></tr></thead><tbody id="ditems"></tbody></table></div><button id="dadd" class="secondary">+ Matériel du dépôt</button><label class="check"><input id="dapprove" type="checkbox">J’ai vérifié le chantier, les quantités et l’état de récupération.</label><div class="actions"><button id="dsave">Enregistrer le bon dans OPUS</button><button id="dpdf" class="secondary">Télécharger le bon interne</button><button id="dlabel" class="secondary">Étiquettes cartons (A6)</button></div><p id="dstatus" role="status"></p></div>`;for(const item of record.items)row(item);if(!record.items.length)row();$('dadd').onclick=()=>row();$('dn').onclick=()=>{if(confirm('Commencer un nouveau bon ? Enregistrez les modifications avant de continuer.')){record=newDepotRecord();baseVersion=null;draw();}};$('dh').onclick=()=>ctx.run(async()=>{history=await records();$('depotHistory').innerHTML=history.map((d,i)=>`<p><button data-open="${i}" class="secondary">${esc(d.number)} · ${esc(d.projectName)} · ${esc(d.state)}</button></p>`).join('')||'<p>Aucun bon interne enregistré.</p>';root.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{if(!confirm('Ouvrir ce bon ? Les modifications non enregistrées seront abandonnées.'))return;record=structuredClone(history[+b.dataset.open]);baseVersion=record.updatedAt;draw();});});
 root.oninput=e=>{root.dataset.dirty='true';if(e.target.id!=='dapprove')$('dapprove').checked=false;};
 $('dpdf').onclick=()=>ctx.run(async()=>{const d=read();ctx.download(await makePDF(depotOrder(d),{logo:await ctx.logo(),project:d.projectName}),'BON_INTERNE_'+safeName(d.number)+'.pdf');});
 $('dlabel').onclick=()=>ctx.run(async()=>{const d=read();ctx.download(await labelPDF(d),'ETIQUETTES_'+safeName(d.number)+'.pdf');});
 $('dsave').onclick=()=>ctx.run(async()=>{const d=read();await ctx.authorize();$('dstatus').textContent='Enregistrement…';const all=await records(),current=all.find(x=>x.id===d.id);if((current?.updatedAt||null)!==baseVersion)throw Error('Ce bon a changé sur un autre ordinateur. Actualisez le suivi et rouvrez-le.');const revision=crypto.randomUUID(),now=new Date().toISOString();const f=await folder(),orders=await ctx.g().folder(d.projectId,'03_COMMANDES'),dest=await ctx.g().folder(orders.id,'DEPOT_BUC');const pdf=await makePDF(depotOrder(d),{logo:await ctx.logo(),project:d.projectName});const item=await ctx.g().upload(dest.id,safeName('BON_INTERNE_'+d.number+'_'+d.state+'_'+revision.slice(0,6))+'.pdf',pdf);try{await ctx.g().writeJson(f.id,d.id+'_'+revision+'.json',{...d,updatedAt:now,pdfId:item.id,pdfName:item.name});record={...d,updatedAt:now};baseVersion=now;root.dataset.dirty='false';$('dstatus').textContent='Bon et suivi enregistrés dans '+d.projectName+' / Dépôt de Buc.';ctx.status($('dstatus').textContent);}catch(e){$('dstatus').textContent='PDF enregistré dans le chantier, mais suivi non enregistré. '+e.message;throw Error($('dstatus').textContent);}});
 }
 function row(v={}){const tr=document.createElement('tr');tr.innerHTML=['reference','description','quantity','unit'].map(k=>`<td><input data-k="${k}" value="${esc(v[k]||'')}"></td>`).join('')+'<td><button>×</button></td>';tr.querySelector('button').onclick=()=>{tr.remove();$('dapprove').checked=false;};$('ditems').append(tr);}
 function read(){const project=ctx.projects().find(p=>p.id===$('dproject').value);const d={...record,date:$('ddate').value,projectId:project?.id||'',projectName:project?.name||'',state:$('dstate').value,recipient:$('drecipient').value.trim(),collectedAt:$('dcollected').value,boxes:Number($('dboxes').value),notes:$('dnotes').value,items:[...$('ditems').rows].map(tr=>Object.fromEntries([...tr.querySelectorAll('input')].map(i=>[i.dataset.k,i.value.trim()])))};validateDepot(d);if(!$('dapprove').checked)throw Error('Relisez et cochez la validation du bon interne.');record=d;return d;}
 draw();
}
