const EXPECTED='opuselec@hotmail.com';
const ROOT='https://graph.microsoft.com/v1.0/';
export const SUPPLIERS=['Rexel','Sonepar','YESSS','Sylvania','CLAREO','ElecDirect','Exertis','UGF','ARIC'];
export function supplierOf(m){const s=[m.from?.emailAddress?.address,m.from?.emailAddress?.name,m.subject].join(' ').toLowerCase();return SUPPLIERS.find(x=>s.includes(x.toLowerCase()))||(/yes{2,}/.test(s)?'YESSS':'Autres');}
export function graphUrl(path){const u=new URL(path,ROOT);if(u.origin!=='https://graph.microsoft.com'||!/^\/v1\.0\/me(?:\/|$)/.test(u.pathname))throw Error('Adresse Outlook non autorisée.');return u.href;}
export function createMailbox(getToken,request=fetch){return async path=>{const r=await request(graphUrl(path),{headers:{Authorization:'Bearer '+await getToken(),Prefer:'outlook.body-content-type="text", IdType="ImmutableId"'},signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error(r.status===401?'Reconnectez votre boîte Outlook.':r.status===403?'La lecture des e-mails doit être autorisée dans Microsoft (Mail.Read).':r.status===429?'Outlook reçoit trop de demandes. Réessayez dans quelques instants.':'Lecture Outlook impossible (HTTP '+r.status+').');return r.json();};}
export function messageText(m,doc=document){let text=m.body?.content||m.bodyPreview||'';if(m.body?.contentType?.toLowerCase()==='html'){const d=doc.implementation.createHTMLDocument('');d.body.innerHTML=text;d.querySelectorAll('script,style,iframe,object,img,link').forEach(x=>x.remove());d.querySelectorAll('br,p,div,tr,li').forEach(x=>x.append('\n'));text=d.body.textContent;}return `De : ${m.from?.emailAddress?.address||''}\nObjet : ${m.subject||''}\nDate : ${m.receivedDateTime||''}\n\n${text}`;}
export function mountOutlook({host,onImport,authorize,download}){
 const el=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e;};
 host.className='card';host.hidden=true;host.innerHTML='<h2>E-mails fournisseurs</h2><p>Boîte : opuselec@hotmail.com · classement indicatif par expéditeur et objet. Les messages restent dans Outlook.</p><details id="mailSetup"><summary>Activer la connexion Outlook (première utilisation)</summary><p>Suivez le guide ACTIVATION_OUTLOOK_V14.txt, puis collez ici l’identifiant d’application (client). Ce n’est pas une clé secrète.</p><input id="mailClient" aria-label="Identifiant d’application Outlook"><button id="mailConfig">Enregistrer la configuration</button></details><div class="actions"><button id="mailConnect">Connecter ma boîte Outlook</button><button id="mailDisconnect" class="secondary">Déconnecter Outlook</button></div><p id="mailStatus" role="status"></p><div class="grid"><label>Depuis le<input id="mailSince" type="date"></label><label>Fournisseur<select id="mailSupplier"><option value="">Tous les fournisseurs</option></select></label><label>Rechercher dans les messages chargés<input id="mailSearch" type="search" placeholder="Commande, référence, chantier…"></label></div><button id="mailRefresh">Rechercher les e-mails</button><p id="mailCount"></p><div id="mailList"></div><button id="mailMore" class="secondary" hidden>Charger les messages suivants</button><section id="mailPreview" hidden><h3 id="mailSubject"></h3><pre id="mailBody" style="white-space:pre-wrap;max-height:350px;overflow:auto"></pre><div id="mailAttachments"></div><p>Seul ce message sera repris. Cliquez ensuite sur « Lire la commande » pour transmettre son contenu à l’IA.</p><button id="mailUse">Utiliser cet e-mail pour le bon</button></section>';
 const $=id=>host.querySelector('#'+id);for(const s of [...SUPPLIERS,'Autres']){const o=el('option',s);o.value=s;$('mailSupplier').append(o);}
 const key='opus-outlook-client-id';$('mailClient').value=localStorage.getItem(key)||'';$('mailSince').value=new Date(Date.now()-90*86400000).toISOString().slice(0,10);
 let client,account,mailbox,next='',rows=[],selected,busy=false;
 const status=t=>$('mailStatus').textContent=t;
 async function run(fn){if(busy)return;busy=true;host.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){status(e.message||'Connexion Outlook impossible.');}finally{busy=false;host.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 function clear(){account=null;mailbox=null;rows=[];selected=null;next='';$('mailList').replaceChildren();$('mailPreview').hidden=true;$('mailBody').textContent='';$('mailAttachments').replaceChildren();$('mailMore').hidden=true;$('mailCount').textContent='';}
 async function setup(){const id=$('mailClient').value.trim();if(!/^[\da-f]{8}(-[\da-f]{4}){3}-[\da-f]{12}$/i.test(id))throw Error('Renseignez l’identifiant d’application Microsoft en suivant le guide V14.');const M=await import('../vendor/msal.js');client=new M.PublicClientApplication({auth:{clientId:id,authority:'https://login.microsoftonline.com/consumers',redirectUri:new URL('./outlook-auth.html',location.href).href},cache:{cacheLocation:'memoryStorage'}});await client.initialize();localStorage.setItem(key,id);}
 $('mailConfig').onclick=()=>run(async()=>{clear();await setup();status('Configuration enregistrée. Cliquez sur Connecter ma boîte Outlook.');});
 $('mailConnect').onclick=()=>run(async()=>{await authorize();clear();if(!client)await setup();const r=await client.loginPopup({scopes:['User.Read','Mail.Read'],loginHint:EXPECTED,prompt:'select_account'});account=r.account;const api=createMailbox(async()=>{if(!account)throw Error('Connectez votre boîte Outlook.');try{return(await client.acquireTokenSilent({scopes:['User.Read','Mail.Read'],account})).accessToken;}catch{throw Error('Session Outlook expirée. Cliquez sur Connecter ma boîte Outlook.');}});const me=await api('me?$select=mail,userPrincipalName');if(![me.mail,me.userPrincipalName,account?.username].some(v=>String(v||'').toLowerCase()===EXPECTED)){clear();await client.clearCache();throw Error('Choisissez le compte '+EXPECTED+'.');}mailbox=api;status('Boîte connectée. Cliquez sur Rechercher les e-mails.');});
 $('mailDisconnect').onclick=()=>run(async()=>{clear();await client?.clearCache();status('Outlook déconnecté de cette fenêtre.');});
 function render(){const q=$('mailSearch').value.toLowerCase(),f=$('mailSupplier').value;const visible=rows.filter(m=>(f?supplierOf(m)===f:supplierOf(m)!=='Autres')&&[m.subject,m.from?.emailAddress?.address,m.bodyPreview].join(' ').toLowerCase().includes(q));$('mailList').replaceChildren();for(const m of visible){const b=el('button',`${supplierOf(m)} · ${new Date(m.receivedDateTime).toLocaleDateString('fr-FR')} · ${m.subject||'(Sans objet)'} — ${m.from?.emailAddress?.address||''}`);b.className='secondary';b.style.cssText='display:block;width:100%;text-align:left;margin:6px 0';b.onclick=()=>run(()=>open(m));$('mailList').append(b);}$('mailCount').textContent=`${visible.length} message(s) affiché(s) sur ${rows.length} chargé(s).`+(next?' D’autres messages sont disponibles ci-dessous.':' Fin des messages pour cette période.');$('mailMore').hidden=!next;}
 async function page(path){if(!mailbox)throw Error('Connectez votre boîte Outlook.');const d=await mailbox(path);const seen=new Set(rows.map(x=>x.id));rows.push(...(d.value||[]).filter(x=>!seen.has(x.id)));next=d['@odata.nextLink']||'';render();status('E-mails chargés. Choisissez un message.');}
 $('mailRefresh').onclick=()=>run(async()=>{if(!mailbox)throw Error('Connectez votre boîte Outlook.');const since=$('mailSince').value;if(!/^\d{4}-\d{2}-\d{2}$/.test(since))throw Error('Choisissez une date de début.');rows=[];next='';selected=null;$('mailPreview').hidden=true;await page('me/messages?'+new URLSearchParams({'$select':'id,subject,from,receivedDateTime,bodyPreview,hasAttachments','$orderby':'receivedDateTime desc','$filter':`receivedDateTime ge ${since}T00:00:00Z`,'$top':'100'}));});
 $('mailMore').onclick=()=>run(()=>page(next));$('mailSupplier').onchange=render;$('mailSearch').oninput=render;
 async function open(m){selected=null;$('mailPreview').hidden=true;const full=await mailbox('me/messages/'+encodeURIComponent(m.id)+'?$select=id,subject,from,receivedDateTime,body,hasAttachments');selected=full;$('mailSubject').textContent=full.subject||'(Sans objet)';$('mailBody').textContent=messageText(full);$('mailAttachments').replaceChildren();if(full.hasAttachments){const note=el('p','Pièces jointes : téléchargez le document utile puis ajoutez-le dans « Captures, photos ou PDF » du bon.');$('mailAttachments').append(note);let path='me/messages/'+encodeURIComponent(m.id)+'/attachments?$select=id,name,size,contentType,isInline';do{const d=await mailbox(path);for(const a of d.value||[]){if(a.isInline)continue;const b=el('button',a.name+' — Télécharger');b.className='secondary';b.onclick=()=>run(async()=>{if(a.size>20000000)throw Error('Pièce jointe supérieure à 20 Mo : ouvrez-la dans Outlook.');const f=await mailbox('me/messages/'+encodeURIComponent(m.id)+'/attachments/'+encodeURIComponent(a.id));if(!f.contentBytes)throw Error('Cette pièce jointe doit être ouverte dans Outlook.');const data=Uint8Array.from(atob(f.contentBytes),c=>c.charCodeAt(0));download(new Blob([data],{type:f.contentType||'application/octet-stream'}),f.name);});$('mailAttachments').append(b);}path=d['@odata.nextLink']||'';}while(path);}$('mailPreview').hidden=false;}
 $('mailUse').onclick=()=>run(async()=>{if(!selected)throw Error('Sélectionnez un e-mail.');await authorize();if(confirm('Reprendre cet e-mail et vider les anciennes sources du bon ?')){onImport(messageText(selected));host.hidden=true;}});
 return {show(){host.hidden=!host.hidden;},};
}
